### ISSUE TITLE
User - Projekteinladung // 5

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#105]
Als Nutzer des Systems möchte ich nach dem ich die Einladung zu einem Projekt bekomme ablehnen und akzeptieren können.

**Akzeptanzkriterien**
- [ ]  Der Nutzer sollte die Einladung ablehnen können
- [ ] Bei Annahme soll ein bestehender WiMi weiterhin WiMi bleiben
- [ ] Falls der Nutzer noch keine Rolle hat wird er HiWi des Projekts

![capture](https://cloud.githubusercontent.com/assets/9438971/11762887/a81cdaec-a0f5-11e5-8d97-68c8ed584d10.PNG)

**Comment by WGierke** [comment]
Das hier soll beachtet werden ![Bild](https://slack-files.com/files-tmb/T0B692A1L-F0GDMPPST-3b23ff493f/pasted_image_at_2015_12_11_01_56_pm_1024.png)
Relevant aus #88

**Comment by WGierke** [comment]
Bleibt ein WiMi bei Annahme einer Einladung Wimi seines alten Lehrstuhls oder wird er WiMi des neuen Lehrstuhls?

**Comment by mockingbird2** [comment]
Der Wimi wechselt seinen Lehrstuhl nicht nach Projekteinladung.
