### ISSUE TITLE
Dokument - Eingabemasken für Reisekostenabrechnung erstellen //15P

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#112]
Ergänzung zu #16

**Akzeptanzkriterien**
- [x] Der Nachname wird nicht mehr angezeigt, da er aus dem Profil befüllt wird
- [x] Der Vorname wird nicht mehr angezeigt, da er aus dem Profil befüllt wird
- [x] Localisation
- [x] Es gibt einen Button zur Auswahl, ob eine Unterschrift hinzugefügt werden soll oder nicht
- [x] Akurate Beschriftung für Public Transport und Vehicle Advance
- [x] Ein Textfeld hinter jeder F/M/A CheckBox Reihe ist vorhanden, um Details bezüglich des Essens zu dokumentieren

*Wichtig, gegf. PDF Erzeugung anpassen*

![capture](https://cloud.githubusercontent.com/assets/9438971/11837992/88974774-a3e4-11e5-97aa-2c5974c9871f.PNG)
![capture](https://cloud.githubusercontent.com/assets/9438971/11837974/666a08ee-a3e4-11e5-90cd-c312392e06db.PNG)

**Comment by Chaoste** [comment]
When adding the annotation for breakfast/lunch/dinner as attribute of report items also add the placeholder in "app/views/documents/Reisekostenantrag.html.erb".

**Comment by tbjoern** [comment]
@Chaoste bitte noch den Reisekostenantrag.html.erb aktualisieren
