### ISSUE TITLE
Dokument - Eingabemasken für Dienstreiseantrag erstellen //10P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#14]
Als Wissenschaftlicher Mitarbeiter möchte ich einen Dienstreiseantrag ausfüllen und in Form einer PDF (#18) downloaden/ausdrucken/speichern können.

**Benötigte Felder**
- Name
- Dienstreiseziel
- Grund für Dienstreise
- Tabelle mit (Reisetag [von,bis,Tage,davon Auslandstage])
- Anmerkungen
- Datum/Unterschrift (Antragssteller) (siehe auch #11)

Tasks:
-View erstellen
-Werte auslesen
-model in db ablegen
-Funktionen für pdf (downloaden, speichern)

**Akzeptanzkriterien**
- [x] Alle benötigten Felder lass sich ausfüllen und abspeichern
- [x] Es gibt einen Knopf zum Drucken/Exportieren als PDF

![capture](https://cloud.githubusercontent.com/assets/9438971/11625742/8a11e342-9cdd-11e5-86a1-886ac66af762.PNG)

**Comment by WGierke** [comment]
Das Ticket ist mit 'done' und 'ready-for-review' gelabeled, aber die Tests laufen [nicht](https://travis-ci.org/hpi-swt2/wimi-portal/builds/93182293) durch. Wurde es komplett auf die anderen Tickets aufgesplitted oder übersehe ich was anderes?

**Comment by tbjoern** [comment]
Das Ticket habe ich zusammen mit Ticket #16 bearbeitet. Die aktuellen changes für beide Tickets befinden sich in dem dazugehörigen Branch.
