### ISSUE TITLE
Superadministrator - Login // 10

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#153]
Als Superadministrator habe ich einen separaten Login der vom openID Login entkoppelt ist.

**Akzeptanzkriterien**
- [ ] Der Login ist unter <localhost>/superadmin erreichbar
- [ ] Der Login funktioniert mittels Benutzername und Passwort
- [ ] Im Profil kann ich mein Passwort ändern. Dazu muss ich mein altes Passwort eingeben und dann 2x mein Neues.

**Comment by WGierke** [comment]
Kann der Benutzername durch eine initiale E-Mail-Adresse ersetzt werden?
Die E-Mail-Adresse kann nach dem Einloggen zusammen mit dem Passwort im Profil geändert werden.
Es muss nicht einmal eine richtige E-Mail-Adresse sein, es wäre nur um einiges leichter und schöner, wenn kein neues Username-Feld angelegt und zum Einloggen verwendet werden müsste.
