### ISSUE TITLE
Bugs in Workdays

### ISSUE THREAD

**Issue by bahnfahren** [hpi-swt2/wimi-portal#172]
- [x] Die Zeitfelder sollten nicht die ganze Zeile lang sein und beide sollten in eine Zeile
- [x] Bitte expect statt should in Tests verwenden (should ist deprected)

**Comment by Sephor** [comment]
Soweit ist das gefixt, die selections füllen aber nicht die ganze Zeile, sondern rechts ist noch eine kleine Lücke. vielleicht kann sich das mal jemand angucken der mehr Ahnung von css hat.
