### ISSUE TITLE
Fix Reisekostenabrechnung

### ISSUE THREAD

**Issue by arneboockmeyer** [hpi-swt2/wimi-portal#173]
- [ ] Wenn general_advance nil ist -> Fehler (default ist aber auch nil)
- [ ] In der Anzeige für jede Mahlzeit nicht true oder false anzeigen, sondern etwas schöneres
- [ ] Eine Mahlzeit kann Frühstück, Mittagessen und Abendessen zugleich sein

**Comment by mandyklingbeil** [comment]
Datepicker nicht notwendig, da das Datum direkt von der entsprechenden Dienstreise übernommen wird.

**Comment by tbjoern** [comment]
Die Bugs sind mit dem PR #142 gefixt.
