### ISSUE TITLE
Fix Navbar kürzen

### ISSUE THREAD

**Issue by maikz** [hpi-swt2/wimi-portal#175]
Wenn die Emailadresse zu lang ist, verschiebt sich diese in der Navigationsleiste nach unten. Alle Navigationselemente sollen in einer Zeile stehen.

**Comment by mandyklingbeil** [comment]
Dieser Fix ist nicht notwendig, da sich die Navbar verändern wird und sich damit das Problem automatisch löst. Folgt in Sprint 4.
