### ISSUE TITLE
Projects - 3 Bugs

### ISSUE THREAD

**Issue by bahnfahren** [hpi-swt2/wimi-portal#182]
- [x] Seitenüberschrift ist 'Title'
- [x] bei demodaten passiert dass chair.representative nil ist und nil kennt keine user-methode
- [x] wenn man aus einem Projekt austritt kann man _scheinbar_ nicht mehr wieder eintreten

(show.html.erb)
<dl class="dl-horizontal">
  <dt><%= t('.chair', default:'Chair') %>:</dt>
  <dd><%= @project.chair.name %></dd>
  <dt><%= t('.chair_representative', default: 'Chair Representative') %>:</dt>
  <dd><%= @project.chair.representative.user.name %></dd>
  <dt><%= t('.project_visibility', default:'Visibility') %>:</dt>
  <dd><%= @project.public ? t('.public', default:'Public') : t('.private', default:'private') %></dd>
  <dt><%= t('.project_leader', default: 'Project Leader') %>:</dt>
  <dd>
    <%if @project.project_leader.blank? %>

**Comment by tbjoern** [comment]
Wenn man aus einem Projekt austritt soll man auch nicht wieder eintreten koennen, dazu braeuchte man wieder eine Einladung. So hatte ich das zumindest verstanden.

**Comment by tbjoern** [comment]
Welche Demodaten meinst du denn ? Wenn man einen Chair erstellt ist Representative ein Pflichtfeld, das sollte also nicht nil werden koennen.

**Comment by naechtner** [comment]
@bahnfahren was ist mit punkt 1 gemeint?
punkt 2 sollte bereits von @shorschig mit [issue 229](https://github.com/hpi-swt2/wimi-portal/issues/229#issuecomment-173212988) erledigt worden sein.

**Comment by threxx** [comment]
@naechtner ja Punkt 1 ist nun bei mir im PR drin

**Comment by naechtner** [comment]
@bahnfahren hast du einen exakten Fall für den dritten Punkt? Bin gerade einmal durchgegangen und nachdem ich mich beworben hatte, angenommen wurde, das Projekt wieder verlassen habe, konnte ich mich wieder bewerben.
