### ISSUE TITLE
Superadministrator - Titel Vergabe // 5

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#191]
Als Superadmistrator kann ich mir selber keine anderen Rollen zuweisen wie z.B. bei der Projekterstellung.

**Akzeptanzkriterien**
- [ ] Dem Superadmin kann keine andere Rolle zugewiesen werden.
- [ ] Der Superadmin kann sich auch selbst keine andere Rolle zuweisen

**Comment by NHoff95** [comment]
Tasks:
- [ ] Superadmin kann nicht WiMi eines Lehrstuhls werden
- [ ] Superadmin kann nicht mehr Lehrstuhlbeauftragter werden
- [ ] Superadmin kann nicht mehr Lehrstuhl-Admin werden
- [ ] Superadmin kann nicht Mitglied eines Projekts werden und nicht eingeladen werden
- [ ] weitere Stellen, an denen Superadmin Rolle einnehmen kann, suchen
