### ISSUE TITLE
Superadministrator - Detailseite Fachgebiet

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#192]
Als Superadministrator möchte ich eine Detail Seite für Lehrstühle einsehen können, nach dem klicken auf den Namen eines Lehrstuhls auf dem Dashboard. Grafisch lässt es sich ähnlich visualisieren wie die Grafik bei #52. Auf dieser Seite will der Superadministrator einen "Bearbeiten" Button haben Felder anzupassen.

**Akzeptanzkriterien**
- [x] FG - Beauftragter muss als Feld zu sehen sein
- [x] Eine Liste aller Wimis ist zu sehen 
- [x] Button zum Bearbeiten von Feldern

**Comment by chrisma** [comment]
Editing the attributes of chairs already works (see screenshot), however, users cannot be removed from chairs.
This is handled by #408

![selection_014](https://cloud.githubusercontent.com/assets/1652117/16436492/90faae02-3d9e-11e6-9621-94a05f480931.png)
