### ISSUE TITLE
Implement notifications for project invitations | 5

### ISSUE THREAD

**Issue by Chaoste** [hpi-swt2/wimi-portal#194]
Use the new event system so the invitations shows up in the notification block on the dashboard (instead of an own block).

**Akzeptanzkriterien**
- [ ] Wenn ein WiMi zu einem Projekt eingeladen wurde, wird die Benachrichtigung im Benachrichtigungs-Feld seines Dashboards angezeigt

**Comment by derari** [comment]
"Invitations sind tot" -- Nietzsche, oder so...
