### ISSUE TITLE
Profilanzeige Urlaub/Dienstreisen/Stundenzettel

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#201]
Als Nutzer möchte ich nur für mich relevante Informationen auf meinem Profil sehen und nur ich darf auf diese Informationen Zugriff haben (mit Ausnahme des FG-Beauftragten):

Als normaler User (ohne Rolle):
- nur persönliche Daten
- keine Antragsübersichten (!)

Als Wimi:
- Übersicht für Urlaubsanträge
- Übersicht für Dienstreise-Anträge

Als Hiwi:
- Übersicht für Stundenzettel

**Comment by derari** [comment]
Ist mehr oder weniger erledigt
