### ISSUE TITLE
Superadmin: Fachgebiet erstellen 

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#205]
Aktuell muss der Superadministrator sowohl einen FG-Beauftragten als auch einen FG-Admin anlegen, um ein Fachgebiet zu erstellen. Notwendig sollte beim initialen Erstellen keiner sein.

**Comment by arneboockmeyer** [comment]
Sind inzwischen nicht mehr notwendig.
