### ISSUE TITLE
User in ein Projekt einladen

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#207]
Einladung funktioniert per E-Mail-Adresse, aber nicht über eine User-Suche. Es sollten beim Eintippen der ersten Buchstaben bereits User-Vorschläge auftauchen. Gebe ich etwas fehlerhaft ein und klicke trotzdem auf "Submit", sollte eine entsprechende Fehlermeldung als Alert kommen (aktuell: Translation missing). 

Nach Einladen eines Nutzers: Lehnt dieser Nutzer die Einladung ab, sollte eine wiederholte Einladung möglich sein. Das Einladen eines Nutzers in ein Projekt sollte jederzeit möglich sein, soweit der Nutzer nicht im Projekt ist.

Wenn die Einladung abgelehnt wurde, aber woanders (in einem anderen Browser z.B.) die Session noch läuft und man dort noch auf Akzeptieren klicken kann, sollte das Akzeptieren nicht mehr möglich sein.

**Comment by WGierke** [comment]
Durch das Fixen der JS-Skripte mit Locales in #231 wird das Skript nun weiter ausgeführt, das für die Vorschläge zuständig ist. Gegenwärtig probiere ich ein Gem zum Testen von JS zu installieren, was inzwischen aber schon seit zehn Minuten installiert ... Wenn es vielversprechend ist, schreibe ich für die Vorschlagfunktion noch einen Test ;)
