### ISSUE TITLE
Projektübersicht fehlerhaft

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#213]
Wenn ich auf der Projektsseite bin, sollte als Überschrift nur der Name des Projekts dastehen (aktuell steht dort z.B. "Project #2: Name des Projekts". 

Es fehlt der Edit-Button auf der rechten Seite neben dem Projektnamen.

Der Teamleiter kann rausgenommen werden.

"Show all working hours" wird als Button 2x angezeigt. Aktionen sollen generell unter Anfragen, aber über die Auflistung der Mitglieder angezeigt werden. 

Wimis oder Hiwis sollen auf der Projektseite aufgelistet werden. Die Namen sollen jeweils auf das Profil verlinken. Für die Auflistung bietet es sich an, eine Tabelle zu benutzen und dort links den Namen aufzulisten und rechts neben dem Namen zwei weitere Spalten anzulegen, um Links für "Stundenzettel anzeigen" oder "Aus Projekt austragen" anzuzeigen. 
Eine Tabelle wird am Ende der Seite angezeigt, obwohl sie ungenutzt scheint...? (Guter Vergleich: Aktuelle Chair-Seite, dort werden die Mitglieder so ähnlich aufgeführt.)

Anbei nochmal das Mock-up:
![bildschirmfoto 2016-01-18 um 09 51 46](https://cloud.githubusercontent.com/assets/7271491/12386957/6b3fbc84-bdc9-11e5-9985-97cdf83c825f.png)

**Comment by threxx** [comment]
@mandyklingbeil der 'edit' button war noch nie oben rechts neben dem Namen, sondern unten. Wenn es unbedingt gewollt ist, kann ich den Button auch noch verschieben, aktuell ist er, wie gesagt, ganz unten neben dem 'back' button und div. anderen Buttons

**Comment by mandyklingbeil** [comment]
@threxx: Gut so, danke. Und einen back-Button sollte es dort gar nicht geben... 

Eigentlich dürfte es überhaupt nirgends eine "Ansammlung" von Buttons geben :)

**Comment by threxx** [comment]
@mandyklingbeil okay, das heißt der delete button sollte auch zu den Actions?

**Comment by mandyklingbeil** [comment]
@threxx Delete? So wie in: Projekt löschen? Das sollte nur unter Projekt bearbeiten möglich sein (nicht direkt auf der Projektseite).

**Comment by threxx** [comment]
@mandyklingbeil okay, dann entferne ich den auf der show Seite

**Comment by mandyklingbeil** [comment]
@threxx :+1:
