### ISSUE TITLE
local parameter 'en' and 'de' in URL should be present

### ISSUE THREAD

**Issue by threxx** [hpi-swt2/wimi-portal#216]
The parameters in the URL where removed as they did not worked well. However the javascript stuff in holidays and projects needs these parameters in order to identify the languages. Therefore these parameters should be added again and fix to work fine with the selected language.

**Comment by WGierke** [comment]
Can I solve the JS stuff problem in another way than reintroducing the GET params?

**Comment by threxx** [comment]
I think the POs want them back anyway. @mockingbird2 ?

**Comment by mockingbird2** [comment]
I suppose the deletion of the paramter caused an amount of errors. Due to url parsing and building translation on top of it.
