### ISSUE TITLE
Stundenzettel - Anzeige mehrerer Projekte auf dem Profil

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#217]
Wenn ich als Hiwi auf mein Profil gehe, sehe ich unter Stundenzettel eine Auflistung meiner Projekte jeweils pro Monat. 

Als Nutzer sollte ich nicht auf den Monat klicken können (die Übersicht ALLER Stunden des Monats einzusehen, ist nicht vorgesehen). Darüber hinaus sollten die Projekte mit einem Komma getrennt aufgeführt werden. Beim Hovern sollte der Projektname blau werden (nicht unterstrichen), um ihn als Link optisch zu kennzeichnen (aktuell: siehe Screenshot).

![bildschirmfoto 2016-01-18 um 10 07 04](https://cloud.githubusercontent.com/assets/7271491/12387263/9ed83664-bdcb-11e5-8f65-18ee9e14b1b4.png)

**Comment by Sephor** [comment]
Derzeit sind alle links so hervorgehoben. Heißt das du willst, dass die css für alle Links geändert wird?

**Comment by mandyklingbeil** [comment]
@Sephor: Bei Fragen mich gerne mit @ markieren. Ansonsten: Ja, dann bitte für alles Links ändern.
