### ISSUE TITLE
Business Trip

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#219]
- [ ] Bei der Erstellung eines Business Trip mit negativer 'Days Abroad' gibt es einen Fehler

Detailseite eines Business Trip
- [ ] UI
- [ ] Es gibt aktuell zwei Hinweise bei der Bearbeitung/Erstellung eines Trips
- [ ] Download in Show PDF umbenennen

![screen shot 2016-01-18 at 10 09 18](https://cloud.githubusercontent.com/assets/9438971/12387369/492e2312-bdcc-11e5-8632-3ee54b50b87d.png)

Detailseite bearbeiten Business Trip
- [ ] UI

**Comment by Zanthelo** [comment]
@sleighsoft welcher von den beiden Hinweisen soll denn angezeigt werden und welcher nicht?

**Comment by sleighsoft** [comment]
Ist repariert!
