### ISSUE TITLE
Seiten ohne Berechtigungen trotzdem erreichbar

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#226]
- [ ] Sämtliche URLs die eine Rolle voraussetzten (z.B.: projects/new | /chairs) sollen auch nur mit dieser Rolle erreichbar sein

**Comment by marcelja** [comment]
für chairs, travel_expense_reports, holidays und trips sollte das jetzt funktionieren. Um die anderen Sachen können wir uns später noch mal kümmern

**Comment by arneboockmeyer** [comment]
Gibts einen PR?

**Comment by marcelja** [comment]
ne, wir haben die bugs direkt im dev gefixt

**Comment by tbjoern** [comment]
Welche URLs sind noch nicht gefixt ?

**Comment by marcelja** [comment]
time_sheets sind noch nicht gefixt.

**Comment by derari** [comment]
Rechtesystem wurde grunderneuert
