### ISSUE TITLE
Create valid demonstration data

### ISSUE THREAD

**Issue by arneboockmeyer** [hpi-swt2/wimi-portal#229]

**Comment by arneboockmeyer** [comment]
See history the seed file.

**Comment by swt-r0ckz** [comment]
Some data can be found in lib/tasks/db.rake .
To load it use: 'rake db:add_demo_data'

**Comment by shorschig** [comment]
Is there a specific reason you didn't put it directly in the seeds.rb?

**Comment by swt-r0ckz** [comment]
Once, it has been in seeds.rb, but I didn't take that out.

**Comment by WGierke** [comment]
Ich hatte auch mal einen Kommentar in die seeds eingefügt, der das erklärte:
In den seeds stehen nur Instanz-Erzeugungen, die für die Funktion des Projekts unabdingbar sind, zB die Erstellung des Superadmins.
Test-Daten sollten davon abgekopselt in einen eigenen Rake-Task kommen, weil sie eben nicht mandatory sind.

**Comment by WGierke** [comment]
@shorschig wieso hast du das Ticket geschlossen?

**Comment by shorschig** [comment]
naja, weil die daten aus dem demo-data task sowie die aus der seeds.rb und das war das kriterium, oder nicht?

**Comment by WGierke** [comment]
Der Task enhält noch keine Trip-, Publication-, TimeSheet-, WorkDays-, ... Instanzierungen. 
Ich denke, der Gedanke hinter dem Ticket ist eher, dass man von so vielen verschiedenen Objeken wie möglich Instanzen durch einen Task erstellen kann. Wenn die Datei leer wäre, wäre ja auch alles valide, aber niemandem geholfen :)

**Comment by shorschig** [comment]
Ah, alles klar

**Comment by shorschig** [comment]
see PR #237
