### ISSUE TITLE
Indexseiten - Bei leeren Tabellen von x nur eine Nachricht "No x yet"

### ISSUE THREAD

**Issue by bahnfahren** [hpi-swt2/wimi-portal#235]
zB "No Business Trips yet"

**Comment by bahnfahren** [comment]
Welche Seiten wären denn alles davon betroffen?

**Comment by tbjoern** [comment]
@bahnfahren Projekte und Chairs vllt noch ?

**Comment by bahnfahren** [comment]
ok mach ich für TimeSheets , Projekte und Chairs
