### ISSUE TITLE
Projects - Projekt ohne Chair erstellbar

### ISSUE THREAD

**Issue by Zanthelo** [hpi-swt2/wimi-portal#236]
Wenn man ein Projekt erstellt, ohne dass es einen Chair gibt, wird ein Fehler geworfen:
undefined method `name' for nil:NilClass
in
app/views/projects/show.html.erb

Das Projekt wird aber trotzdem erstellt und jedes Mal wenn man auf die Seite des Projekts geht bekommt man den selben Fehler.

**Comment by bahnfahren** [comment]
siehe auch https://github.com/hpi-swt2/wimi-portal/issues/182 für weitere bugs mit projects

**Comment by threxx** [comment]
@Zanthelo ich glaub diesen Bug gibt es nicht mehr im dev, sollte bereits behoben sein

**Comment by threxx** [comment]
@mockingbird2 diesen Fehler gibt es nicht mehr!

**Comment by mockingbird2** [comment]
Dann wäre es schön, wenn die Entwickler in Zukunft das Issue Tracking benutzten und gelöste Probleme auch schließen.
