### ISSUE TITLE
User Interface - Navigation durch das System //3P/0P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#24]
Als Nutzer möchte ich mit nur einem Klick zu meinem Profil und zu meinem Dashboard gelangen. Die Navigationsleiste soll nur zentrale Elemente enthalten. Die Anzeige meiner E-Mail-Adresse ist dort nicht notwendig.

**Akzeptanzkriterien**
- [x] Als eingeloggter Nutzer erreiche ich mein Profil von jeder Seite aus mit einem Klick. 
- [x] Als eingeloggter Nutzer erreiche ich das Dashboard von jeder Seite aus mit einem Klick.

**Comment by marcelja** [comment]
Voraussetzung ist das Dashboard #17.
Im Moment gibt es noch kein Profil für Users, Link führt zu '/users/edit'. Das müsste noch mal angepasst werden, wenn Profile eingeführt wurden.
