### ISSUE TITLE
Workdays - Sind ohne Chair und Projekt erstellbar

### ISSUE THREAD

**Issue by bahnfahren** [hpi-swt2/wimi-portal#241]

**Comment by Sephor** [comment]
Bitte etwas genauer. Ich kann keine work_days ohne Projekt erstellen. Wie hast du es geschafft?

**Comment by Sephor** [comment]
Falls du meinst, dass man nicht auf die new Page kommen soll wenn man auf der work_day Seite ohne Projekt ist dann ist das mit #217 gefixt.

**Comment by Sephor** [comment]
Issue ist identisch mit #217
