### ISSUE TITLE
Dashboard - Zeitpunkt der Notifications anzeigen

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#259]
Als Nutzer möchte ich zu allen Notifications auf meinem Dashboard sehen, wann (Datum, Uhrzeit mit Stunde:Minute) die Notification bei mir eingegangen ist. 

**Akzeptanzkriterien**
- [ ] Anzeige von Datum und Uhrzeit zu allen Notifications
- [ ] Beispiel: Reicht einer der Hiwis von meinen Projekten einen Stundenzettel ein, möchte ich als Wimi eine Notification auf meinem Dashboard darüber, neben der Datum und Uhrzeit dazu angezeigt werden.

**Comment by chrisma** [comment]
![selection_018](https://cloud.githubusercontent.com/assets/1652117/14564501/152e1856-0327-11e6-9241-9ee6d4d1cef1.png)

**Comment by chrisma** [comment]
Notifications should have a `created_at` attribute.

**Comment by chrisma** [comment]
Duplicate: https://github.com/hpi-swt2/wimi-portal/issues/546
