### ISSUE TITLE
Urlaubsantrag - Optik anpassen 

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#260]
Gleiche Optik für die Detailseiten aller Anträge. 

Beispiel: Die Detailseite des Urlaubsantrags ist nicht stimmig. Die Daten befinden sich in einem Panel, während das bei anderen Anträgen nicht so ist, z.B. auf der Detailseite von Dienstreise-Anträgen.

**Comment by arneboockmeyer** [comment]
Solved in #311
