### ISSUE TITLE
Foreign user profil shows options to change password

### ISSUE THREAD

**Issue by threxx** [hpi-swt2/wimi-portal#261]
When visiting an foreign user profil to see the name and stuff, the following content is shown:

![screen shot 2016-01-27 at 13 17 26](https://cloud.githubusercontent.com/assets/7422033/12613264/d38bdbca-c4f8-11e5-871a-a6bc474aa78c.png)

In my opinion, no other user should be able to see the 'change password' window, except the user itself.

Note: the text 'You are not member of a chair' should be changed to something like: 'This user is not member of a chair'

**Comment by Sephor** [comment]
Bist du superuser?

**Comment by threxx** [comment]
nein.

<img width="589" alt="screen shot 2016-01-27 at 13 24 38" src="https://cloud.githubusercontent.com/assets/7422033/12613342/546a5dca-c4f9-11e5-8ce5-243679744203.png">

**Comment by Sephor** [comment]
Fixed with #298
