### ISSUE TITLE
Überschriften einzelner Seiten

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#276]
Jede Seite sollte eine Überschrift haben. Diese sollte nicht zu groß sein (nicht h1!). 

Die Überschrift soll dem Nutzer Kenntnis darüber geben, wo er sich im System gerade befindet. Ist er zum Beispiel gerade auf dem Dashboard? Sieht er sich gerade die Detailseite eines Urlaubsantrags an? 

Wenn der Nutzer selbst die Details seiner Anträge einsieht, so reicht eine Überschrift, die darüber informiert, welchen Antrag er gerade einsieht. Sieht der FG-Beauftragte die Details für einen Antrag eines Wimis ein, ist es notwendig, auch zu sehen, von wem der Antrag gestellt worden ist.

**Comment by arneboockmeyer** [comment]
Solved in #311
