### ISSUE TITLE
Superadministrator - Login

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#280]
1. Es ist derzeit nicht möglich sich parallel als Benutzer und als Superadministrator anzumelden
2. Ist man als Nutzer (openID) eingeloggt und geht auf die Seite <url>/superadmin so wird das Login Feld angezeigt. Jedoch kann man sich nicht als Superadmin anmelden, da man bereits als Nutzer eingeloggt ist.

**Erwartetes Verhalten**
- Man kann sich parallel als Benutzer und als Superadministrator anmelden (2 unabhängige Sessions)

**Comment by tbjoern** [comment]
Das steht im Konfikt zu Issue #267

**Comment by WGierke** [comment]
Der User kann auch einfach ein privates Fenster öffnen :)

**Comment by bahnfahren** [comment]
Schließen?

**Comment by sleighsoft** [comment]
Nicht schließen, wenn ihr das schon nicht so wie bei *Erwartetes Verhalten* anpassen wollte, dann macht wenigstens einen redirect, sodass ich wenn ich bereits eingeloggt bin nicht nochmal ein sinnloses Login Feld für den Superadministrator sehe

**Comment by arneboockmeyer** [comment]
Ja der Redirect ist umgesetzt.
