### ISSUE TITLE
Superadministrator - Funktionen

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#281]
1. Der Superadministrator hat derzeit Zugriff auf alle Funktionen eines Nutzers/Wimis

**Erwartetes Verhalten**
- Der Superadministrator hat keinen Zugriff auf Funktionen von Benutzern/Wimi (Anträge, Profil, Projekte o.ä.). Er kann lediglich Lehrstühle erstellen und Zuständige festlegen
- Der Superadministrator kann in seinem Profil nur sein Passwort ändern

**Comment by tbjoern** [comment]
Ergaenzung: Momentan sind Signature, User Data und Time sheet overview zu sehen.

**Comment by NHoff95** [comment]
@mockingbird2 @mandyklingbeil @sleighsoft Ein Superadministrator soll Lehrstühle auch bearbeiten/löschen dürfen, oder? Aktuell sieht er zwar vorhandene Lehrstühle auf dem Dashboard, aber er kann nichts mit ihnen machen, weil nichts weiter verlinkt ist.

**Comment by mockingbird2** [comment]
Ja der Superadministrator soll erstellte Lehrstühle bearbeiten und löschen können.

**Comment by NHoff95** [comment]
D. h. wie möchtet ihr es gern? Einfach Buttons neben dem Lehrstuhl wie auch auf der Lehrstuhl-Übersichtsseite? Oder anders?

**Comment by mockingbird2** [comment]
Ich glaube es genügt wenn auf der Lehrstuhlübersichtsseite es implementiert ist. Das Dashboard ist halt die reine Übersicht ohne weitere Funktionalität

**Comment by NHoff95** [comment]
@mockingbird2 OK, finde ich eigentlich auch am sinnvollsten, aber nach der Navbar-Story #132 hat der Superadmin keinen Link mehr zu dieser Seite in der Navigationsleiste. Man erreicht die Seite aktuell nur über den direkten Link.

**Comment by mockingbird2** [comment]
@NHoff95 Wenn es keine Lehrstuhlübersichtsseite mehr gibt, dann soll das löschen und bearbeiten auf dem Dashboard geschehen

**Comment by NHoff95** [comment]
@mockingbird2 Naja, es gibt sie schon noch und andere User haben auch noch einen Link dahin, nur der Superadmin eben nicht mehr. Aber OK, dann mache ich also Buttons auf das Dashboard...
