### ISSUE TITLE
Profil

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#282]
Vorbedingung: Eingeloggt als FG-Beauftragter eines Lehrstuhls

1. Aktuell ist es möglich auf dem Profil eines anderen Nutzers, der am eigenen Lehrstuhl ist, die Anzahl seiner verfügbarer Urlaubstage zu ändern

**Erwartetes Verhalten**
- Es ist nicht möglich für einen anderen Nutzer die Anzahl seiner verfügbaren Urlaubstage zu verändern

**Comment by Tymolc** [comment]
Ist das eine geänderte Anforderung? In Issue #57 wurde das nämlich noch explizit so verlangt.

**Comment by Tymolc** [comment]
@sleighsoft ?
