### ISSUE TITLE
Wenn ein Projekt keinen Chair hat, kann '/projects' nicht angezeigt werden

### ISSUE THREAD

**Issue by marcelja** [hpi-swt2/wimi-portal#285]

**Comment by tbjoern** [comment]
Wie kann man das reproduzieren @marcelja ?

**Comment by marcelja** [comment]
durch `Project.create(title: "test", public: true)`

Da Projekte aber wohl einen Chair haben müssen, würde es reichen, `validates :chair, presence: true` zum Projekt-Model hinzuzufügen.
