### ISSUE TITLE
Stundenzettel

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#288]
**Aktuell**
1. Wenn ich als Nutzer den Link auf einen Stundenzettel habe, so kann ich diesen einreichen, obwohl es nicht mein eigener ist.
2. Es gibt zwei unterschiedliche Stundenzettel Seiten
3. Fremde Nutzer können meine Stundenzettel sehen
4. Als FG-Beauftragter gibt es eine Auflistung der Hiwis unter 'Research Groups' und hinter jedem Hiwi einen Eintrag 'Show Timesheets'. Dieser macht jedoch aktuell nichts!

https://wimi-portal-dev.herokuapp.com/work_days?month=1&user_id=3&year=2016
![pasted image at 2016_01_28 02_49 pm 1](https://cloud.githubusercontent.com/assets/9438971/12646117/70feb78a-c5ce-11e5-9587-3e9553de57b3.png)

Anzeige dieser Seite nicht nötig!
https://wimi-portal-dev.herokuapp.com/work_days?month=12&project=5&user_id=3&year=2015
![pasted image at 2016_01_28 02_49 pm](https://cloud.githubusercontent.com/assets/9438971/12646120/724d3c42-c5ce-11e5-900e-bdaa8f0b5562.png)

**Erwartetes Verhalten**
1. Wenn ich einem Projekt (https://wimi-portal-dev.herokuapp.com/projects/5) auf 'Show Working Hours' klicke, dann möchte ich auf eine Seite geleitet werden, die die Arbeitsstunden dieses Projekts auflistet (siehe Bild 1)
2. Eine Auflistung aller Arbeitsstunden in einem Monat ist nicht nötig und kann entfernt werden
3. Es ist nicht möglich fremde Stundenzettel einzusehen/einzuhändigen
3.1. Einsehen ist nur möglich, wenn ich Wimi des Projekts bin in dem der Hiwi ist und der Hiwi den Stundenzettel eingehändigt hat
4. Erstellt man einen neuen Stundenzetteleintrag so soll für das Datum bereits 'Datum von heute' vorausgefüllt sein. Dies kann man aber auch ändern.
5. Wenn bei 'edit' eines Stundenzettels auf 'Back' gedrückt wird, so landet man wieder bei (siehe Bild 1)
6. 'Show Timesheets' wird entfernt (außer Funktionalität davon ist schon irgendwo implementiert, dann korrekt verlinken und alle PO benachrichtigen)
7. Es soll die Summe aller bis jetzt eingetragenen Stunden angezeigt werden. Oberhalb von 'Add Signature' (siehe Bild 1)

**Comment by Chaoste** [comment]
Der letzte Punkte wurde bereits umgesetzt. Den Rest habe ich umgesetzt und dabei auch an anderen Stellen, die mir aufgefallen sind, Sachen gefixt. Die View für alle Workdays (ohne Projekt) gibt es nicht mehr. Dafür gibt es aber neu die View über alle Monate in einem Projekt für den Button "Show all workdays" in der projekt-ansicht.
