### ISSUE TITLE
PDF - Reisekosten

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#292]
**Aktuell**
1. Es lässt sich die Zeit für Start und Ende der Reise auswählen, diese ist jedoch nicht korrekt im PDF, dort steht jeweils 00:00.

**Erwartetes Verhalten**
- Zeit wird korrekt im PDF angezeigt

**Comment by shorschig** [comment]
Auf welches konkrete PDF bezieht sich das?

**Comment by Chaoste** [comment]
Ich übernehme gern, da die PDFs mein Reich sind :P

**Comment by Chaoste** [comment]
Dieser Bug existiert nicht
