### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#300]
Bei jeder User Notification soll der Text auch per Email an den jeweiligen User gesendet werden, über die hinterlegte Email. Im Profil sollten die Emails per Flag ausschaltbar sein

**Comment by sleighsoft** [comment]
Diese Story gibt es schon in #295 !

**Comment by WGierke** [comment]
@marcelja wenn du das machst, schließe ich das Ticket jetzt. Sag mir aber, wenn du irgendwo Unterstützung brauchst :)

**Comment by marcelja** [comment]
okey, mache ich :)
