### ISSUE TITLE
Superadministrator - Rolle // 3

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#31]
Als 'Superadministrator' kann ich Lehrstühle erstellen.
Als 'Superadministrator' kann ich einem 'User' die Rolle 'Administrator' eines Lehrstuhls zuweisen, wenn ein Lehrstuhl existiert.
Als 'Superadministrator' kann ich einem 'User' die Rolle 'Lehrstuhlsbeauftragter' eines Lehrstuhls zuweisen, wenn eine Lehrstuhl existiert.

Wichtig: Es gibt im System initial immer einen 'User' mit den Rechten eines  'Superadministrator'.

**Akzeptanzkriterien**
- [ ] Nach dem Erstellen eines Lehrstuhls kann dieser eingesehen werden #25
- [ ] Ist eine Lehrstuhl erstellt, so kann ich einem 'User' die Rolle 'Administrator' dieses Lehrstuhls zuweisen

**Comment by arneboockmeyer** [comment]
Schätzung: 13

**Comment by mockingbird2** [comment]
Nachträglich soll der SuperAdmin auch noch Admins von Lehrstühlen hinzufügen können. Es sollen auch sollen auch die Rechte von bestehenden Admins entfernt werden können.
