### ISSUE TITLE
Es existieren keine Löschkaskaden

### ISSUE THREAD

**Issue by bahnfahren** [hpi-swt2/wimi-portal#315]
Beispiel: Chair wird gelöscht, aber alle Projekte zum Chair existieren noch, dann geht man auf die Projects Index Seite und bekommt error weil project.chair nil ist.

Also, entweder werden Löschkaskaden eingebaut, oder solche Sachen werden abgefangen...

**Comment by Zanthelo** [comment]
Wenn ein Projekt gelöscht wird, werden alle noch ausstehenden Einladungen und notifications nicht gelöscht
