### ISSUE TITLE
Dashboard - Link zu Expenses

### ISSUE THREAD

**Issue by swt-r0ckz** [hpi-swt2/wimi-portal#323]
Es wird ein Fehler geworfen, wenn man als Representative auf 'Show expense requests' auf dem Dashboard klickt.

**Comment by Zanthelo** [comment]
@swt-r0ckz Was genau geht da nicht? Bei mir funktioniert das

**Comment by swt-r0ckz** [comment]
Wenn du einen Expense-Request erstellst und ihn einreichst, dann funktioniert dieser Link nicht mehr.
