### ISSUE TITLE
Login unmöglich bei invalider E-Mail Adresse

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#344]
Wenn der ein User keine valide Email Adresse angibt, blockiert dieser das komplette System und kein weiterer User kann sich anmelden.

**Comment by arneboockmeyer** [comment]
Siehe auch #206

**Comment by mockingbird2** [comment]
In #206 ging es ja bisher nur darum, dass man sich selbst nicht mehr einloggen kann, was gefixt wurde. Jetzt kann sich aber niemand anderes mehr einloggen.

**Comment by arneboockmeyer** [comment]
Das war auch nur als Crossreferenz gedacht und nicht als Duplikat ;) Aber wenn #206 gefixt ist, kann der ja geschlossen werden.

**Comment by mockingbird2** [comment]
Ein Teil von #206 existiert noch, wenn man nicht zustimmt bei openID die email Addresse zu übertragen, sollte man trotzdem im System eine eintragen können, was nicht funktioniert.

**Comment by derari** [comment]
Scheint kein Problem mehr zu sein...
