### ISSUE TITLE
Übersicht eines Chairs enthält "Show timesheets" Strings statt buttons

### ISSUE THREAD

**Issue by arneboockmeyer** [hpi-swt2/wimi-portal#346]
Weiterhin gibt es auf der Chair/show bei den Hiwis ein 'Show timesheets', was allerdings nur ein String ist. (Bild 2)

![bildschirmfoto von 2016-02-04 10 00 01](https://cloud.githubusercontent.com/assets/11941962/12810451/ac38be60-cb26-11e5-8455-65761f0f5de4.png)

**Comment by tbjoern** [comment]
Im akutellen Master ist das nicht drin.
