### ISSUE TITLE
Lehrstuhlbeauftragten setzen

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#347]
Es ist nicht möglich einen Lehrstuhlbeauftragter als Superadmin für einen Lehrstuhl zu setzen. Bei der Auswahl lässt sich eine Person auswählen, aber nach der Aktualisierung ist das Feld wieder leer.

**Comment by NHoff95** [comment]
@mockingbird2 Habe ich eben probiert und konnte es bei mir nicht reproduzieren. Gibt es für dieses Problem bestimmte Voraussetzungen?

**Comment by mockingbird2** [comment]
Nachdem ich es gerade mit leerer datenbank nochmal probiert habe kam der fehler nicht mehr. Ich mach es wieder zu.
