### ISSUE TITLE
Lehrstuhlbeauftragter überall

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#348]
Wenn man einen Lehrstuhlbeauftragten gesetzt hat an irgendeinem Lehrstuhlt wird dieser auch automatisch Lehrstuhlbeauftragter an allen anderen Lehstühlen.

**Comment by NHoff95** [comment]
@mockingbird2 Auch das ließ sich bei mir nicht reproduzieren.

**Comment by mockingbird2** [comment]
Das gleiche auch hier, nach erneutem aufsetzen verschwand der Fehler.
