### ISSUE TITLE
Profil - Unterschrift verschlüsseln Spike // 3P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#35]
Sich darüber informieren, wie die sichere Verschlüsselung einer hochgeladenen Unterschrift (als jpg/png) funktioniert funktioniert / wie viel Aufwand sie macht. (siehe #11)

**Comment by JuliusTreike** [comment]
It is possible to save your pictures encoded with base64 and decode them like in this example:
http://stackoverflow.com/questions/1547008/how-to-encode-media-in-base64-given-url-in-ruby

Der Aufwand ist also nicht so groß, aber eine hunderprozentige Sicherheit ist nicht gewähleistet, da wenn ein Angreifer, sie haben möchte und weiß, womit verschlüsselt wurde, kann er sie wieder entschlüsseln.
Da Bilder benutzt werden sollen, ist es nicht möglich diese zu hashen, wie es mit Passwörtern gemacht wird, weswegen eine hundertprozentige sichere Abspeicherung wegfällt.

**Comment by WGierke** [comment]
Base64 ist keine Verschlüsselung sondern eine Kodierung.

**Comment by mandyklingbeil** [comment]
@JuliusTreike: Die Aufgabe ist es, eine sichere Verschlüsselung zu implementieren. Bitte recherchiere weiter, vielleicht findest du ja eine Lösung mit AES-256 oder so.
