### ISSUE TITLE
Allow WiMi to be in multiple projects simultaneously

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#358]
At the moment, every WiMi can only be assigned to a single project.

**Comment by derari** [comment]
@chrisma review plz

**Comment by chrisma** [comment]
See Comments to commit 40c789f043a322cc9e3908aa041dd713d2feb351

https://github.com/hpi-swt2/wimi-portal/commit/40c789f043a322cc9e3908aa041dd713d2feb351
