### ISSUE TITLE
Invite WiMi to research group

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#361]
As a chair admin/representative, I want to invite users to be WiMis.

**Comment by chrisma** [comment]
It should be possible to invite people to be WiMis of a chair at the chair's detail page (e.g. http://portal.eaalab.hpi.uni-potsdam.de/chairs/1), similarly to how HiWis can be invited to projects.

![selection_012](https://cloud.githubusercontent.com/assets/1652117/14492896/957a67ae-0182-11e6-8893-e89eae2192b6.png)

**Comment by chrisma** [comment]
Users do not need to be "invited". A head of department / assistant can add users to chairs, making them wimis. There is no need for confirmation on the wimi user side.

**Comment by chrisma** [comment]
A notification on the wimi side would be nice.
The activity log should be updated the the info that there is a new wimi.

**Comment by chrisma** [comment]
Adding WiMis to a chair was implemented in #397.
Notifications are handled by #405.
