### ISSUE TITLE
External login

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#364]
As a user without an HPI openId account, I should be able to login with name+password

**Comment by derari** [comment]
when trying to log in with a wrong password, user should be redirected to login page

**Comment by chrisma** [comment]
working on this in the `redirect_invalid_login` branch.

**Comment by chrisma** [comment]
![selection_030](https://cloud.githubusercontent.com/assets/1652117/14670930/81349d06-06ef-11e6-9ac3-6332f34b71c3.png)
![selection_031](https://cloud.githubusercontent.com/assets/1652117/14670929/8114db2e-06ef-11e6-8049-0e765e7f4ebf.png)
