### ISSUE TITLE
Prefill project when adding workday

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#372]
When I am on a project's detail page (`/projects/1`) and I add a new workday ('add workday' button, `/work_days/new`), the 'project' form field should be filled with the project that I came from.

![selection_026](https://cloud.githubusercontent.com/assets/1652117/14637043/32f3d316-062f-11e6-9a9e-fbce547b7e45.png)
![selection_027](https://cloud.githubusercontent.com/assets/1652117/14637044/32f49594-062f-11e6-930f-b5068dee5f9c.png)

**Comment by derari** [comment]
TODO: check if `work_days/new` actually checks the project parameter

**Comment by chrisma** [comment]
This is really two separate issues: The URL parameter "project" that is passed to the "New Workday" page doesn't select the right project in the dropdown + The selected project in the dropdown is not saved correctly.
