### ISSUE TITLE
Do not display empty 'Actions' boxes

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#376]
Currently the 'Actions' box in the right column of the page gets rendered, even if no actions are available, e.g. on `projects/<id>`.
If no actions are available, no box should be rendered.

![selection_036](https://cloud.githubusercontent.com/assets/1652117/14822836/76714e42-0bd0-11e6-92ff-61ed5ec95b75.png)

**Comment by tbjoern** [comment]
3d49e68657aea63b196b994f31475fbf57f1ae0a
