### ISSUE TITLE
Send invitations to non-existing users

### ISSUE THREAD

**Issue by tkowark** [hpi-swt2/wimi-portal#377]
When inviting a user to a project, I get the "User does not exist" warning. Would be cool, if instead you send out an email to that person asking them to register as a new user

**Comment by chrisma** [comment]
Thanks! :+1:
Maybe something along the lines of

> Hello,
> you have been invited to join the {project} project on the WiMi-Portal of the Hasso-Plattner Institute.
> Please visit {host} and log-in with your HPI credentials.
> If you do not have an HPI account, please E-Mail {superadmin_email}
> Thanks!
> Wimi-Portal Team

Creation of new accounts by users is not yet available, see #380

**Comment by tbjoern** [comment]
TODO: move identity url prefix to config via ENV variable
add button for adding the user via the email on projects#show
send email to user
auto create a contract -> checkbox (set sensible defaults for contract)
