### ISSUE TITLE
Urlaubsantrag shows wrong numbers

### ISSUE THREAD

**Issue by tkowark** [hpi-swt2/wimi-portal#379]
I created my first "Urlaubsantrag" for 1 day and in the PDF it says that I have 32 days total, already took 4 and have 24 remaining. Where do these numbers come from???

**Comment by chrisma** [comment]
The system should allow setting your own amount of remaining leave on the "Profile" page.
There is definitely something fishy with the way that the numbers on the PDF are calculated though...
I feel that some of the numbers might be switched.

![selection_038](https://cloud.githubusercontent.com/assets/1652117/14850685/06dc736c-0c7b-11e6-85b8-5c82fb112f27.png)
