### ISSUE TITLE
Invalid E-Mail on OpenID sign-in

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#382]
After initial sign-in, the E-Mail field is filled with "invalid_email".
This is probably due to the HPI-OpenID service not sending back E-Mail addresses correctly for non-student members.
Instead of filling the field with a predefined string, the user should be informed that E-Mail retrieval failed and that the field needs manual editing if E-Mail notifications are desired.

<img width="347" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/1652117/14881203/4b39f044-0d33-11e6-8000-62bf63a528a1.png">

**Comment by tbjoern** [comment]
if a users `email == User::INVALID_EMAIL` the user is automatically redirected to his profile with the flash message "please set a valid email address first". They cannot take any other action until they provide a valid email address.

**Comment by chrisma** [comment]
Is a valid email address actually needed for any part of the system?
I feel that the only drawback of an empty / invalid email field would be that we cannot send notifications

**Comment by chrisma** [comment]
Anyway, it should definitely be `email == nil`, I see no benefit in having the `INVALID_EMAIL` constant

**Comment by tbjoern** [comment]
openid needs some value to satisfy the model validation when it creates the user. if openid does not provide an email, we need to give it some value so it validates successfully.
