### ISSUE TITLE
Remove personnel_number from users

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#383]
Every user has a numerical "personnel_number" attribute (displayed as `Staff Number`) that can be set in the profile.
As far as I can tell, this is not needed for the system.
As it stands it is confusing. Can it be removed?

<img width="433" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/1652117/14881681/62d15fba-0d35-11e6-8f2b-5e43a9c22534.png">

**Comment by tbjoern** [comment]
Its used for pdf printing as stated in #412 , closing this.
