### ISSUE TITLE
Timesheets not viewable if HiWi left project

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#385]
If a HiWi hands in a timesheet and then leaves the project, the timesheet is no longer viewable.
For example, clicking the "inspect" button on the user profile does not work.

![selection_040](https://cloud.githubusercontent.com/assets/1652117/14884304/1a7a0726-0d44-11e6-8f68-a0576c5bfe0f.png)

**Comment by derari** [comment]
timesheets are no longer linked to projects
