### ISSUE TITLE
Don't show chair representative on project page

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#386]

**Comment by derari** [comment]
Fixed in dev

@chrisma this change caused 4 tests to fail. If anything in this application was tested as well as *"project page shows chair rep"* ......

**Comment by chrisma** [comment]
Looks good to me, thanks! :+1:
CI looks [good](https://travis-ci.org/hpi-swt2/wimi-portal/builds/126436559) as well (except the deploy errors, ofc)

**Comment by chrisma** [comment]
Everything merged to master. Will Deploy after successful build.
