### ISSUE TITLE
Overflowing text for long project names

### ISSUE THREAD

**Issue by FHorschig** [hpi-swt2/wimi-portal#388]
Long project names like "High Performane In-Memory Genome Project" flow over the margins of their button AND the background itself.
As such long names are usual, this might be worth looking into.

**Comment by chrisma** [comment]
![css_sucks](https://cloud.githubusercontent.com/assets/1652117/15823874/e2d91eb0-2bfc-11e6-90e6-0be4ddc5558e.png)

**Comment by chrisma** [comment]
Thanks for the report!

**Comment by chrisma** [comment]
The overview of "time sheets of your students" was removed from the user detail page.
