### ISSUE TITLE
Add button for working hours is in a very unintuitive place

### ISSUE THREAD

**Issue by FHorschig** [hpi-swt2/wimi-portal#389]
A user usually never looks at the top right of the page for the main operation. That's rather a place for alternatives.
Please tie the functionality to the place where it belongs. In this case: why don't you put the 'add workday'-button right beneath the collection of existing work days?

**Comment by chrisma** [comment]
![weird_button](https://cloud.githubusercontent.com/assets/1652117/15827118/86529668-2c0a-11e6-99db-c564785b67d2.png)

**Comment by chrisma** [comment]
Thanks for the detailed feedback!

**Comment by chrisma** [comment]
Navigation links for the previous / next month were implemented in #420.
The 'add' button is currently still in its original place as it allows reaching it easily, even if the list of workdays is already long. We will evaluate this in the next user test.
