### ISSUE TITLE
Projekte - Projekt hinzufügen // 2

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#39]
Als Beauftragter/Admin des Fachgebiets und als 'WiMi' hab ich auf der Übersichtsseite der Projekte einen Button, um neue Projekte hinzuzufügen.

**Akzeptanzkriterien**
- [ ] Ein Button mit 'Projekt hinzufügen' wird auf der Seite angezeigt
- [ ] Ein Klick auf den Button bringt mich auf die Seite, auf der neue Projekte erstellt werden können

![bildschirmfoto 2015-11-24 um 21 39 17](https://cloud.githubusercontent.com/assets/7271491/11380022/d6af8a22-92f3-11e5-90c5-59b965ed5ea7.png)

**Comment by sleighsoft** [comment]
Diese Story fällt mit https://github.com/hpi-swt2/wimi-portal/issues/37 zusammen und wird damit obsolete.

**Comment by mockingbird2** [comment]
Die User Story ist bereits abgenommen und in der Code Review @sleighsoft dein Team muss sich dann den Code von dem jeweiligen Branch holen.
