### ISSUE TITLE
Add contracts model

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#396]
As a chair assistant, I want to manage hiwi contracts.

* A contract belongs to a hiwi and a responsible wimi
* Time sheets belong to a contract
* Work days belong to a user. 
  * For reporting, they can also belong to a project
  * They are mapped to time sheets based on their date

### Other Changes
* Chair and project applications and invitations are about to be removed
* Inviting user to chair or project should add them instantly. 
  * ~~Doesn't work right now~~ (done in #397)
* ~~The rights for business trips, holidays and expenses need to be added again~~ (now in #406)

**Comment by derari** [comment]
@chrisma check the new hotness in town

**Comment by chrisma** [comment]
\o/ Thanks!

**Comment by chrisma** [comment]
I think this is done.
Re-adding the rights for business trips, holidays and expenses is in a new ticket: #406
