### ISSUE TITLE
Unify User autocompletion

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#397]
Many forms require to input a user and have some form of auto completion. It should work consistently on all pages.

- [x] Contract form
- [x] Add user to project
- [x] Add user to chair

**Comment by derari** [comment]
According to Matthias, users should be identified by their user name. cf #399

**Comment by derari** [comment]
also related: #361

**Comment by chrisma** [comment]
Instead of inviting users, add them directly to the project. No confirmation is needed on hiwi side.
![selection_054](https://cloud.githubusercontent.com/assets/1652117/15895461/c2004750-2d8b-11e6-8bfb-f6161ff3906c.png)

**Comment by chrisma** [comment]
8e6b24a2bda074242f403a31993eb1dab60d7e0c allows adding users on the cntract new page
5e23cd899a9b3b1c66a57a8fc94ccfdcb89a17e1 allows adding user to projects
0e0cdfd4343b1581522b1e3b274819b31bde1cc0 allows adding users to chairs
