### ISSUE TITLE
Automatically set username based on email address

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#399]
username field should be set automatically based on local-part of email address

**Comment by chrisma** [comment]
User search (for user autocomplete) relies on first name, last name and email. I don't think any part of the system actually uses the 'username'?
I would vote for simply removing it. @derari What do you think?

**Comment by chrisma** [comment]
@derari ping

**Comment by derari** [comment]
ja kann weg

**Comment by chrisma** [comment]
Ok, ich lass es erstmal drin. Es gibt #383
