### ISSUE TITLE
Projekte - Anzeige // 8

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#40]
Als 'User' kann ich auf der Übersichtsseite für Projekte alle öffentlichen Projekte und alle nicht öffentlichen Projekte, in denen ich Mitglied bin, mit folgender Beschreibung einsehen:

- Name des Projekts
- Fachgebiet des Projekts
- Status des Projekts (aktiv/inaktiv)
- Button/Link, um sich aus dem Projekt auszutragen (falls Mitglied)
- Button/Link, um sich bei einem Projekt einzuschreiben (falls noch kein Mitglied)

**Akzeptanzkriterien**
- [ ] Die oben gelisteten Informationen werden pro Projekt angezeigt
- [ ] Die Buttons werden entsprechend meiner Beziehung zu einem Projekt angezeigt
- [ ] Ein Klick auf den Button 'Aus Projekt austragen' entfernt mich aus dem Projekt
- [ ] Ein Klick auf den Button 'Aus Projekt eintragen' ersetzt den Button durch den Text 'Bestätigung ausstehend'
- [ ] Ein Klick auf den Button 'In Projekt eintragen' schickt eine Beitrittsanfrage an die Projekt-WiMis 

![bildschirmfoto 2015-11-24 um 21 39 17](https://cloud.githubusercontent.com/assets/7271491/11380061/26133d98-92f4-11e5-8881-f8a91b4d14a3.png)

**Comment by arneboockmeyer** [comment]
Wie wird man Mitglied in einem nicht öffentlichen Projekt?

**Comment by mandyklingbeil** [comment]
Über eine Einladung von einem Wimi, der Mitglied im Projekt ist.

**Comment by threxx** [comment]
Tasks:

- [ ] Die oben gelisteten Informationen werden pro Projekt angezeigt
- [ ] Die Buttons werden entsprechend meiner Beziehung zu einem Projekt angezeigt
- [ ] Ein Klick auf den Button 'Aus Projekt austragen' entfernt mich aus dem Projekt
- [ ] Ein Klick auf den Button 'Aus Projekt eintragen' ersetzt den Button durch den Text 'Bestätigung ausstehend'
- [ ] Ein Klick auf den Button 'In Projekt eintragen' schickt eine Beitrittsanfrage an die Projekt-WiMis
