### ISSUE TITLE
Leaving chairs

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#408]
Only representatives / assistants can remove third parties from chairs. People cannot leave chairs.

**Comment by chrisma** [comment]
This is functionality that should be available on the edit page of chairs, similarly to how it is handled with projects.

![selection_007](https://cloud.githubusercontent.com/assets/1652117/16116787/22a8200c-33cf-11e6-9663-e12219346bf4.png)

![selection_008](https://cloud.githubusercontent.com/assets/1652117/16116793/288cce14-33cf-11e6-883b-de67532b794d.png)

**Comment by derari** [comment]
@chrisma 
> Only representatives / assistants can remove third parties from chairs

is this really a problem?
> This is functionality that should be available on the edit page of chairs

No, it should not. 1) only reps/assistants can edit chair. 2) Employees can remove only themselves. If anything, there should be a "leave" button in the sidebar.

I think this issue should be closed as wont-fix.
