### ISSUE TITLE
Projekt - Informationen anzeigen // 4

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#42]
Als Beauftragter des Lehrstuhls, Wimi oder Hiwi möchte ich auf der Seite eines Projekts folgende Informationen einsehen können:
- den Namen des Lehrstuhls, dem das Projekt zugeordnet ist
- wer Beauftragter des Lehrstuhls ist
- ob das Projekt öffentlich oder nicht öffentlich ist
- wer Teamleiter des Projekts ist
- eine Liste aller WiMis in diesem Projekt
- eine Liste aller HiWis in diesem Projekt

Sollte das Projekt inaktiv sein, so wird dies hinter dem Projektnamen (inaktiv) angezeigt.

- [ ] Die oben genannten Informationen werden auf der Projektseite dargestellt.

![bildschirmfoto 2015-11-24 um 21 55 36](https://cloud.githubusercontent.com/assets/7271491/11380406/1da58650-92f6-11e5-934f-574829d08e32.png)

**Comment by threxx** [comment]
Als Beauftragter des Lehrstuhls, Wimi oder Hiwi möchte ich auf der Seite eines Projekts folgende Informationen einsehen können:

-[ ] den Namen des Lehrstuhls, dem das Projekt zugeordnet ist
-[ ] wer Beauftragter des Lehrstuhls ist
-[ ] ob das Projekt öffentlich oder nicht öffentlich ist
-[ ] wer Teamleiter des Projekts ist
-[ ] eine Liste aller WiMis in diesem Projekt
-[ ] eine Liste aller HiWis in diesem Projekt

**Comment by threxx** [comment]
@mockingbird2 Nachdem ich ein Projekt bearbeitet habe (& auch erstellt), bekomme ich nochmal eine Overview von dem Projekt. Welche Felder sollen dort zu sehen sein? Alle nochmal oder nur bestimmte?
