### ISSUE TITLE
Don't show stats to representatives of other chairs

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#423]
Representatives can view the statistics of reported hours on the chair' detail page.
Representatives should not be able to view the statistics of other chairs.

![selection_016](https://cloud.githubusercontent.com/assets/1652117/16152125/85bd0fa0-34a0-11e6-8d0d-2fc431586d77.png)

**Comment by tbjoern** [comment]
07ffb6c85b56b8afdfc423a0abdefc37cd56f1f0
