### ISSUE TITLE
Restrict access to chairs#index

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#424]
The chairs index page (`/chairs`) doesn't provide a lot of value, especially if one doesn't have edit rights. It only allows you to look at the details of other chairs. Not really a core functionality.
Maybe chairs#index should be restricted to superadmins, who can actually use the page?
Input, @derari ?

![selection_017](https://cloud.githubusercontent.com/assets/1652117/16152632/1f9c881a-34a3-11e6-859e-2c7c7674204b.png)

**Comment by tbjoern** [comment]
what are we doing here? restrict access?

**Comment by chrisma** [comment]
The current behavior of the system is to show the chair's detail page directly, when clicking on the `chairs` tab and only a single chair is accessible to the user.
This is the majority of users and all HiWis, so this is not too important. It doesn't break the UI in a significant way. Closing for now.
