### ISSUE TITLE
Projekt - Administrative Aktionen für WiMi des Projekts // 8

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#43]
Als 'WiMi' eines Projekts kann ich verschiedene Aktionen auf der Projektseite ausführen: 
- Auf "Bearbeiten" klicken und dadurch Name, Sichtbarkeit (öffentlich/nicht öffentlich) sowie Status (aktiv/inaktiv) ändern
- Mich selbst aus dem Projekt austragen
- Einen anderen Wimi/einen Hiwi aus dem Projekt entfernen
- Mit Klick auf "Stundenzettel einsehen" von einem spezifischen Hiwi auf die entsprechende Übersicht gelangen (projektspezifische Arbeitsstunden setzt #59 voraus)
- Auf "Alle Stundenzettel einsehen" klicken und auf die Übersicht der Hiwi-Stundenzettel zum Projekt gelangen (setzt #59 voraus)
- Auf "Jemanden in das Projekt einladen" klicken und über ein Modal einen Nutzer auswählen und zum Projekt einladen

**Akzeptanzkriterien**
- [ ] Nach Klick auf "Bearbeiten" lässt sich der Name des Projekts bearbeiten und speichern
- [ ] Nach Klick auf "Bearbeiten" lässt sich das Projekt 'aktiv' schalten (wenn inaktiv) und umgekehrt
- [ ] Nach Klick auf "Bearbeiten" lässt sich die Sichtbarkeit des Projektes zwischen öffentlich/nicht öffentlich wechseln und speichern
- [ ] Auf der Seite kann ich mich aus dem Projekt austragen (mit zusätzlicher Bestätigung), womit ich meine Rechte in diesem Projekt verliere und es nicht mehr auf meinem Dashboard/Profil angezeigt wird

![capture](https://cloud.githubusercontent.com/assets/9438971/11878676/92e1b336-a4f7-11e5-926c-9246dfd114ac.PNG)

**Comment by WGierke** [comment]
Tasks:
- neue boolsche Attribute für Projekt (Status, Sichtbarkeit) hinzufügen
- projects/edit.html.erb daran anpassen
- zugeordnete Hiwis/Wimis anzeigen sowie in der gleichen Reihe
  * einen Button, der dessen Assoziation zum Projekt löscht
  * einen Button, der zur Übersicht der Stundenzettel des Hiwis an diesem Projekt weiterleitet #59 
- einen Button, der zur Übersicht aller Stundenzettel an diesem Projekt weiterleitet #59

**Comment by mockingbird2** [comment]
Das Einladen zu einem Projekt wird rollenspezifisch. Wenn man einen bestehenden WiMi einlädt, wird dieser WiMi des Projekt. Falls der User noch keine Rollte hatte wird dieser HiWi. Schon angemeldete HiWis bleiben ganz normal bei der Rolle HiWi.

**Comment by WGierke** [comment]
@mockingbird2 Wer hat die Rollen implementiert? Auf dessen Merge müssen wir dann momentan warten.

**Comment by mockingbird2** [comment]
@WGierke Ich glaube du musst dir mal #7 anschauen und mal fragen

**Comment by threxx** [comment]
@mockingbird2 @mandyklingbeil Kann ein Projekt auch von einem Hiwi erstellt werden? Und wenn ja: Wenn man eine Projekt erstellt und dieses speichert, kommt man anschließend nochmal auf eine kurze Projektübersicht, wo ich drei Buttons haben "back', "edit", "destroy". Angenommen ein Projekt wird nun von einem Hiwi erstellt, sieht dieser alle 3 Buttons in diesem Moment oder nur den "back" Button und der Wimi der Projektes könnte dann das erstellt Projekt bearbeiten?
Und die "destroy'-Aktion kann auch nur von dem Wimi des Projektes ausgeführt werden?

**Comment by mockingbird2** [comment]
Als hiwi kann ich keine Projekte erstellen
