### ISSUE TITLE
Export timesheet as pdf without comments

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#430]
When adding work days, a HiWi can add comments on what was done during the logged timeslot.
while this information may be interesting for the WiMi who employed him, it is not necessary to include these comments in the exported timesheet that can be handed in.

There should be an option to hide comments on export.

**Comment by tbjoern** [comment]
implemented in ae82e4b76012898aaffac3125a1f72b7455e6833
no tests yet, i dont know how

**Comment by tbjoern** [comment]
tests not necessary
