### ISSUE TITLE
Tests for work_day#index navigation links

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#431]
There are currently no tests for the links used to switch between months in work_days#index.

![selection_001](https://cloud.githubusercontent.com/assets/1652117/16307424/78cc6b54-3961-11e6-81eb-e2b2cf2a8e66.png)

**Comment by tbjoern** [comment]
this might be irrelevant after the refactoring #454

**Comment by chrisma** [comment]
At least on the `timesheet#view` page, these links should be available to allow viewing the next / previous month's timesheet.

![selection_038](https://cloud.githubusercontent.com/assets/1652117/19070763/2df58d8c-8a2d-11e6-9064-42f8cf5c7bca.png)
