### ISSUE TITLE
Check E-Mail notifications

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#439]
- [x] Get Emails to work
- [ ] Fix ENV so that environment varaibles are preserved through restarts and SSH connections (write environment variables into .bash_profile?)

**Comment by tbjoern** [comment]
What's ENV?

**Comment by chrisma** [comment]
ENV refers to the environment variables which are set in production, so that this data is not in the repo, e.g. `ENV["EMAIL_USER"]` in [production.rb](https://github.com/hpi-swt2/wimi-portal/blob/f0a414daaaf121464d30f60f60b41ba92737392d/config/environments/production.rb)

**Comment by chrisma** [comment]
Notifications for:
* HiWi handed in time sheet
* Time sheet is accepted / rejected by WiMi

**Comment by chrisma** [comment]
Dupe: https://github.com/hpi-swt2/wimi-portal/issues/546
