### ISSUE TITLE
Refactor WorkDays and TimeSheets

### ISSUE THREAD

**Issue by tbjoern** [hpi-swt2/wimi-portal#454]
Currently WorkDays and TimeSheets are implemented rather messy. WorkDays are matched via Month and Date and the whole system is unnecessarily complex.

Refactor it so its easier to use. That means that a TimeSheet belongs to a contract and the workdays belong to a TimeSheet. At the same time work on #452 , the view should be a table where the user can input his working hours.

- [x] refactor structure
- [x] adapt PDF generation
- [x] make form prettier
- [x] auto adjust number of work days according to month and year
- [x] write tests (yes this should come first ;) )

**Comment by derari** [comment]
TODO: talk to Marilena how overlapping contracts/two contracts in one month are handled by HPI. E.g., how many timesheets need to be handed in, who's responsible for signing?
cc @chrisma

**Comment by chrisma** [comment]
Enforce that every work day has a connected project. There should never be any work days that are not connected to a project for accounting reasons.
Maybe also add a test for this?
