### ISSUE TITLE
Come up with some version system

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#458]
So that it's easier to discuss what is deployed and so on.

Also to discuss: https://gist.github.com/stephenparish/9941e89d80e2bc58a153

**Comment by chrisma** [comment]
:+1:

**Comment by tbjoern** [comment]
+1

**Comment by tbjoern** [comment]
This is the last issue of the milestone, lets make a new release (on github) after all the changes are merged into master. I propose we just start at version 0.1 and go from there.

**Comment by chrisma** [comment]
I have deployed the code as of `bbc4f0a` and created a release (v2.0): https://github.com/hpi-swt2/wimi-portal/releases/tag/v2.0
I guess we'll just create a new release whenever we deploy to production. The latest release is then the version that is deployed.
@tbjoern @derari is that ok?
