### ISSUE TITLE
Remove stale branches

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#462]
There are branches like `454_refactor_time_sheets` that are far behind dev and are probably not needed anymore.
Ideally, there are only `dev` and `master` branches, in addition to those branches actively being worked on right now.

**Comment by tbjoern** [comment]
Done. Only branches left are master dev and 454_refactor_time_sheets. I am currently using that one :P

**Comment by chrisma** [comment]
:+1:
