### ISSUE TITLE
Remove 'add working hours' link from profile

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#463]
![selection_025](https://cloud.githubusercontent.com/assets/1652117/18665530/fbbf647e-7f27-11e6-9c0f-6738b22118a1.png)

This link is available both on the dashboard as well as the profile. It makes more sense on the dashboard, imho, so remove it from the profile.

**Comment by tbjoern** [comment]
currently all actions from the dashboard are rendered in the profile, using the dashboard/actions partial. Should we remove it completely ?

**Comment by chrisma** [comment]
Yes, I think so.
Seems counter-intuitive to me to render dashboard actions on the profile (in addition to the dashboard).
The dashboard is a much more central place. A user should not need to visit his profile very often.

**Comment by chrisma** [comment]
If this is done with a partial, avoiding code duplication, this is not important.
