### ISSUE TITLE
Replace AM/PM time entry for work days with 24h input

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#466]
![selection_028](https://cloud.githubusercontent.com/assets/1652117/18667331/6d0978d8-7f30-11e6-9791-02fd081d99e8.png)

**Comment by chrisma** [comment]
Instead of using a time field use a string and parse to a date

**Comment by chrisma** [comment]
```
    delocalize_config = { :date => :date }
    params.require(:work_day).permit(*allowed_params).delocalize(delocalize_config)
```

from `app/controllers/work_days_controller.rb`

**Comment by derari** [comment]
To set up delocalize, add `time/input/formats` to en.yml and de.yml. See `date/input/formats` as example
