### ISSUE TITLE
Move timesheet buttons (hand-in, etc) to sidebar

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#467]
- [x] Move buttons to sidebar
- [x] Make the sidebar be fixed, i.e. don't scroll it.

![selection_029](https://cloud.githubusercontent.com/assets/1652117/18667647/bb5b30b6-7f31-11e6-9a01-0b80be5f740f.png)
![selection_030](https://cloud.githubusercontent.com/assets/1652117/18667673/d7367c6e-7f31-11e6-8c35-cff151c0ef4e.png)

**Comment by tbjoern** [comment]
Moved buttons to sidebar with c0e397155e24e283bf1cdf13cc2bfb1921f3b271
