### ISSUE TITLE
Add timesheet delete button on timesheet#edit

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#472]
![selection_043](https://cloud.githubusercontent.com/assets/1652117/19072177/14838744-8a34-11e6-8223-18fb6671ed25.png)

**Comment by chrisma** [comment]
Deletion is only possible if the timesheet is not handed in already.

**Comment by tbjoern** [comment]
Feature is added, test doesnt work yet. Help please.
