### ISSUE TITLE
Popup for choice of exporting comments on timesheets

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#475]
![selection_045](https://cloud.githubusercontent.com/assets/1652117/19072962/88179c82-8a38-11e6-8db2-1d31a45de245.png)

when clcikling the download button, either on `timesheet#index` or `timesheet#view`, there should be a popup (if the selected timesheet has comments), asking if the comments should be exported as well.

This should be a partial that can be reused.

**Comment by chrisma** [comment]
I like it! :+1:

**Comment by jonathanherdt** [comment]
It is a bit overwhelming to have that pop up every time. Can we have a less intrusive way of controlling this? Like a pop up for the first time and then a setting or a separate field "PDF with comments"?

**Comment by chrisma** [comment]
Hi Jonathan!
Thanks for your comment. I have opened a new ticket for this issue: https://github.com/hpi-swt2/wimi-portal/issues/550. Feel free to add your implementation ideas there.
