### ISSUE TITLE
Stundenzettel - Als Wimi einen Stundenzettel bestätigen // 5P // 1,5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#48]
Als Wimi möchte ich einen Stundenzettel, der von einem meiner Hiwis angefragt wurde, mit meiner Unterschrift bestätigen oder (optional mit Anmerkungen) ablehnen können, um den Prozess schnell und effizient abzuschließen. Dazu möchte ich alle eingetragenen Arbeitsstunden des Hiwis zu einem bestimmten Monat einsehen können. Ich möchte außerdem sehen, wie viele Arbeitsstunden der Hiwi laut Vertrag arbeitet. Ein Hinweis verrät mir, ob das Dokument bereits vom Hiwi unterschrieben worden ist oder nicht.

**Atomic Tasks**
- [x]  3 Buttons hinzufügen 
- [x] Funktionalität für Buttons hinzufügen 
- [x] Tabelle für Stundenzettel anlegen
- [x] Eingereichte Stundenzettel im Profil darstellen
- [x] Nur Eingereichte Stundenzettel anzeigen
- [x] Reject Anmerkungsfeld hinzufügen und übertragen
- [x] Bug fix
- [ ] Rechteverwaltung

**Akzeptanzkriterien**
- [x] Die Wochenarbeitszeit des Hiwis laut Vertrag wird angezeigt.
- [x] Alle vom Hiwi eingetragenen Arbeitsstunden für einen bestimmten Monat werden aufgelistet.
- [ ] Falls keine Unterschrift im Profil hinterlegt ist, öffnet sich bei Klick auf den Button "Unterschreiben"  ein Modal mit dem Hinweis: "Für diese Aktion muss eine Unterschrift im Profil hinterlegt werden." Das Modal bietet zwei Buttons mit den Optionen: "Später hinzufügen" (schließt das Modal) oder "Zum Profil" (leitet zur Profilseite weiter).
- [ ] Nach Klick auf "Unterschreiben" erfolgt ein Alert, dass die Unterschrift erfolgreich eingefügt wurde. Der Button "Unterschreiben" verschwindet.

![bildschirmfoto 2015-11-24 um 20 44 13](https://cloud.githubusercontent.com/assets/7271491/11379596/85495bb0-92f1-11e5-9ec8-0b5c4a897997.png)

![bildschirmfoto 2015-11-24 um 20 57 02](https://cloud.githubusercontent.com/assets/7271491/11379621/95c2db7e-92f1-11e5-8a33-71e7fc3c1e19.png)

![bildschirmfoto 2015-11-24 um 20 44 21](https://cloud.githubusercontent.com/assets/7271491/11379606/8a5b0428-92f1-11e5-9f3a-0ff0dbf31a34.png)

![bildschirmfoto 2015-11-24 um 20 44 33](https://cloud.githubusercontent.com/assets/7271491/11379629/9ba54234-92f1-11e5-98f3-e0005505c369.png)

![bildschirmfoto 2015-11-24 um 21 25 05](https://cloud.githubusercontent.com/assets/7271491/11379682/e2e1dc3e-92f1-11e5-8e3f-f3756d8e97dc.png)

**Comment by Ferandal** [comment]
Wo genau sollen dem Wimi die Stundenzettel angezeigt werden die eingereicht wurden?

**Comment by mandyklingbeil** [comment]
@Ferandal: Da gibt es mehrere Möglichkeiten.

1. Möglichkeit: Auf dem Profil des Hiwis, der den Stundenzettel eingereicht hat. Dort soll es einen Block "Stundenzettel" geben und wie bei den Urlaubsanträgen eine Übersicht erscheinen, wo die Stundenzettel aufgeführt sind und eingesehen werden können (siehe auch 1. Screenshot von #53). 

2. Möglichkeit: Auf einer Gesamtübersicht aller Stundenzettel, die er einsehen darf. Die ist in #47 abgebildet. Der Wimi gelangt auf diese Gesamtübersicht z.B. von seinem Dashboard aus oder von der Seite eines bestimmten Projekts (siehe 1. Screenshot von #43).

**Comment by Ferandal** [comment]
Da es ja jetzt so ist das pro Monat nur ein Stundenzettel zur Verfügung steht ist es doch richtig, wenn ein Studenzettel abgelehnt wurde, er nicht eingefroren wird und der User noch die Möglichkeit hat diesen zu bearbeiten und neu einzureichen oder?

**Comment by mandyklingbeil** [comment]
Ja, so ist es.
