### ISSUE TITLE
Cannot take back handed in timesheets

### ISSUE THREAD

**Issue by jonathanherdt** [hpi-swt2/wimi-portal#489]
I just inadvertently handed in my timesheet because I confused the "New Work Day" with the "Hand In" button. Now that my timesheet is handed in, I cannot do anything anymore. It should be possible to cancel the hand-in process and maybe there should also be a warning if you try to hand in your timesheet in the middle of the month.

**Comment by tbjoern** [comment]
This might be fixed already in the new version. Can we deploy the current dev to the production system @derari @chrisma ?

**Comment by chrisma** [comment]
This looks good! :+1: 
Are there tests for this feature yet?
