### ISSUE TITLE
Unable to clear workday

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#499]
Nils Strelow stellte folgenden Bug fest:

Mir fällt gerade auf, dass man keine Einträge löschen kann.
Also eine Zeile leer machen und speichern, löscht die Einträge nicht.
Und wenn man die Zeit auf 00:00-00:00 mit 0min stellt, aktualisiert sich auch nur die Seite und lässt einen nicht speichern(was ja auch Sinn macht)

- [x] work_days sollten durch das löschen aller Felder gelöscht werden können.

- [x] work_days sollten durch das Eintragen von 0 in start_time, end_time und break gelöscht werden.

@tbjoern Kann das als erstes gemacht werden? Dann kann ich das fix deployen...

**Comment by chrisma** [comment]
@tbjoern Es gibt jetzt einen fehlschlagenden Test für das Feature. Guckst du dir das bitte an?

**Comment by tbjoern** [comment]
one test still fails because the routes are different after a refactor. will be fixed in a different issue.

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335

**Comment by chrisma** [comment]
https://travis-ci.org/hpi-swt2/wimi-portal/builds/173212293#L335
