### ISSUE TITLE
Only allow time sheet creation when there is a current contract

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#506]
If a user attempts to create a time sheet for a month that no contract is available for, there should be an error.

**Comment by chrisma** [comment]
Test added in d6c227e73c7ea7a62d6526c8ed787cadfc12951e

**Comment by chrisma** [comment]
Tests are failing / are incomplete (see https://github.com/hpi-swt2/wimi-portal/commit/5e74e7fef142dd2f62c0f1d5cd6a97d89be04ba1#diff-58f7beb2eda041c25e4fe06b6cd6bbefR29)

**Comment by tbjoern** [comment]
tests are green as of f19d1b0
