### ISSUE TITLE
Auto-format time fields of time sheet

### ISSUE THREAD

**Issue by mathebox** [hpi-swt2/wimi-portal#531]
When editing a time sheet you have to type `10:00` to enter a time.
It would be great if the colon is inserted automatically. So I have only to type `1000`.
I found this feature really handy when using the Excel sheet.

**Comment by chrisma** [comment]
Thanks for the comment!
Good point, entering `1000` should also work.
As a workaround (for now) for full hours it's possible to just enter `10` which will be parsed as `10:00`

**Comment by chrisma** [comment]
Pending feature tests available in `spec/features/time_sheet/work_day_crud_spec.rb`
