### ISSUE TITLE
CSS of navbar is broken on small screens

### ISSUE THREAD

**Issue by mathebox** [hpi-swt2/wimi-portal#532]
Because there are so many entries in the navbar, the CSS breaks on small screens.

![screen shot 2016-12-02 at 15 27 56](https://cloud.githubusercontent.com/assets/1757680/20838175/a7dc777a-b8a7-11e6-8aad-aac3a078a6fb.png)

**Comment by chrisma** [comment]
Thanks for the report!
I presume this is an issue with not using the Bootstrap navbar classes correctly.
The navbar should wrap or show a 'sandwich'  menu on small screens.

**Comment by mathebox** [comment]
The sandwich icon shows up but only for `width <= 768px`.
The navbar breaks for `768px < width < 992px`.

**Comment by tbjoern** [comment]
http://stackoverflow.com/questions/18558881/bootstrap-collapse-bar-turns-transparent-when-window-is-reduced

in our code:
```
.navbar-fixed-top {
    height:50px;
}

**Comment by tbjoern** [comment]
064c6c645aab625ec3ae4ff49814d45684a020c4

**Comment by tbjoern** [comment]
This is broken again, the new icons in the navbar caused that i think

**Comment by chrisma** [comment]
Unfortunately I can't seem to reproduce this.
It looks the following under Chrome (Version 58.0.3029.110 (64-bit)) as well as Firefox (Version 53.0.3 (64-bit)) on Linux.

What problems are you seeing?

![image](https://user-images.githubusercontent.com/1652117/26927394-f7eaa618-4c51-11e7-99dd-041becc8ae3a.png)

**Comment by tbjoern** [comment]
Happens in Firefox 53.0.3 for window widths 994 to 1200

![screenshot_20170612_140512](https://user-images.githubusercontent.com/10194372/27033138-4bc9c376-4f78-11e7-88cd-2eb7b3b63795.png)

**Comment by chrisma** [comment]
Have we possibly stumbled on a Windows-specific problem?

![image](https://user-images.githubusercontent.com/1652117/27033313-03c0fcc4-4f79-11e7-845e-99a83d3921d9.png)
![image](https://user-images.githubusercontent.com/1652117/27033347-36658e56-4f79-11e7-9c7c-5eb9f5f629b2.png)

**Comment by chrisma** [comment]
Relevant code in `app/views/layouts/_navbar.html.erb`
