### ISSUE TITLE
Notifications/Email refactoring

### ISSUE THREAD

**Issue by tbjoern** [hpi-swt2/wimi-portal#544]
Summarizing all the Issues concerning Notifications and Emails. 
There should be notifications for:
- [ ] User is added to Chair / Project -> notify user
- time sheet is 
  - [ ] handed in -> notify representative
  - [ ] accepted -> notify hiwi
  - [ ] rejected -> notify hiwi

All events should be logged to a history

Each notification should also send an email to the respective user.
This can be turned off by the user through the profile settings.
Each notification can be toggled. Emails can also be enabled/disabled completely.

Users can see all notifications on their dashboard page.
Notifications can be dismissed.
Notifications show a datetime of their occurence (date is sufficient)
Notifications link to the subject (i.e. timesheet or chair/project)

ENV is preserved through restarts and ssh connections #439 

There should be tests for all of the above

**Comment by chrisma** [comment]
The following gem might be of use for the "All events should be logged to a history" use case

https://github.com/airblade/paper_trail

**Comment by chrisma** [comment]
Split into #548 and https://github.com/hpi-swt2/wimi-portal/issues/546 containing more details
