### ISSUE TITLE
Create new notification system

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#546]
Events should be rendered in the form: `12.3.16 hh:mm : <message>`

The following events are currently relevant:

| Trigger | Message |
| --- | --- |
| TS hand in | `[Henry Hiwi] handed in time sheet [Hiwi March 16] with responsible [Willy Wimi]` |
| TS accept | `[Willy Wimi] accepted the time sheet [Hiwi March 16] of [Henry Hiwi]` |
| TS reject | `[Willy Wimi] rejected the time sheet [Hiwi March 16] of [Henry Hiwi]` |
| Project create | `[Willy Wimi] created project [ME310]` _(`target_user = user`)*¹_ |
| Project join | `[Willy Wimi] added [Henry Hiwi] to project [ME310]` |
| Project leave | `[Willy Wimi] removed [Henry Hiwi] from project [ME310]` |
| Chair join | `[Willy Wimi] added [Henry Hiwi] to chair [EPIC]` |
| Chair leave | `[Willy Wimi] removed [Henry Hiwi] from chair [EPIC]` |
| Chair add admin | `[Willy Wimi] granted admin rights to [Waldemar Wimi] for chair [EPIC]` |
| Contract create | `[Willy Wimi] created contract [Hiwi (Jan17 - Jan18)] for [Henry Hiwi]` |
| Contract extend | `[Willy Wimi] extended the contract [Hiwi (Jan17 - Jan18)] of [Henry Hiwi]` |

(Markup `[]` represents the `linked_name` of an object, i.e. a link to the object with text `object#name`)

These should be represented by a new `Events` class (the name `Notifications` is already in use by `ActiveRecord::Notifications`) with the fields:
- `created_at: Datetime`, when the event was created, i.e. when the event happened, _required_
- `user: User`, the user that is responsible for triggering the event, _required_
- `object: Polymorphic association` [(rails docu)](http://guides.rubyonrails.org/association_basics.html#polymorphic-associations), the object that was manipulated, _required_
- `target_user: User`, the user that the manipulation is concerned with, e.g. the user who was added to a project object, _required_*¹
- `type: Enum`: Distinct values for every type of event, _required_

Notes: 
- *¹ : If there is no sensible value for the `target_user`field of an event, save the `user` to avoid joining problems with cancan.
- For every type of event the `Event` class should have a custom constructor, e.g. `Event#time_sheet_hand_in`, which checks that the fields required for rendering the event are filled.
- The  different rendering of events is handled by the I18n mechanism: For every event the I18n key `"event.#{event.type}"` is used.
- Only the last 50 events should be shown as a widget on the dashboard.
- Access control, i.e. who can see which notifications, is dealt with in https://github.com/hpi-swt2/wimi-portal/issues/547
- No support for inline actions. In order to react to an event the linked object page should be used.

**Comment by tbjoern** [comment]
Question: How are the access rights to the events? Which notifications does a hiwi / wimi / admin / representative see ? and where would we define the access rights ?

**Comment by chrisma** [comment]
Check the Open issues of the RC5 Milestone. There should be a separate
issue detailing this.

Am 13.02.2017 10:21 vorm. schrieb "Sören" <notifications@github.com>:

**Comment by tbjoern** [comment]
Ah okay, thanks #547

**Comment by tbjoern** [comment]
about the users mail preferences: how do we store this information ?
i see 2 options atm: either have a bitfield, where every index maps to an event type
or store a hash that maps from event type to boolean.

first option is memory efficient but has the disadvantage that if the order of the enums changes the preferences get messed up
second option needs a lot more memory and has the disadvantage that we cant rename the enums afterwards ..

any better ideas ?
