### ISSUE TITLE
Notes / Bemerkungen field too narrow

### ISSUE THREAD

**Issue by jonathanherdt** [hpi-swt2/wimi-portal#549]
The "notes" field is too narrow for how I use it. A typical note for me looks like this: "Documentation Feedback". Sometimes it is much longer still. Currently, all I can see is "Docu", the rest is cut off. This makes inputs and edits hard. A width of 200px or more would be better. 300px would be nice.

Alternatively, if the "Actions" float on the right could be moved to the top, all fields would have lots more space which would make editing a lot more comfortable.

**Comment by chrisma** [comment]
Hi @jonathanherdt .
Thanks for the feedback. Good point. It is hard to input longer strings as notes.

**Comment by tbjoern** [comment]
35698af7a2feff0d3eba46f8334e932c16453406
