### ISSUE TITLE
Wimi - Urlaubsantrag Detailseite // 3P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#55]
Als Wimi möchte ich für meine gespeicherten Urlaubsanträge eine Übersicht haben.

**Akzeptanzkriterien**
- [ ]  Es gibt einen Button "Antrag stellen" mit dem ein noch nicht gestellter Antrag gestellt wird, ansonsten ist der Button nicht sichtbar
- [x] Es gibt ein Button "Bearbeiten", mit dem ich einen noch nicht gestellte Antrag bearbeiten kann
- [x] Es gibt einen Button "PDF anzeigen" mit dem ich den Antrag in PDF Form einsehen ("downloaden") kann.
- [x] Alle Daten aus den Akzeptanzkriterien aus #54 müssen einsehbar sein
- [ ] Jeder Urlaubsantrag hat einen Status. Es gibt 4 Status "bearbeitet" ( zuletzt von dem stellenden WiMi bearbeitet), "eingereicht", "angenommen", "abgelehnt", die jeweils mit einem korrespondierenden Datum angezeigt werden.
- [x] Der Status passt sich dynamisch an, zu dem Stand des Dokument
- [x] Ist der Antrag gestellt, so ist bearbeiten nicht mehr möglich und ein Tooltip beschreibt, dass gestellte Anträge nicht bearbeitet werden können
- [ ] Ist der Antrag abgelehnt, so kann man ihn wieder bearbeiten

**Atomic Tasks**
- [x] Feld für den Grund des Antrags
- [x] Dauer
- [x] Anmerkung
- [x] Vertreter Anzeigen
- [x] pdf Anzeigenbutton
- [x] Einreichebutton
- [x] Bearbeiten Button in Abhängigkeit vom Status

![capture](https://cloud.githubusercontent.com/assets/9438971/11624266/09f5f112-9cd3-11e5-9674-5af9c3c05e1a.PNG)

**Comment by sleighsoft** [comment]
Akzeptanzkriterium ergänzt um Status verständlicher zu machen:
- Ist der Antrag abgelehnt, so kann man ihn wieder bearbeiten
