### ISSUE TITLE
Setting for downloading time sheets with comments.

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#550]
@jonathanherdt [remarked](https://github.com/hpi-swt2/wimi-portal/issues/475#issuecomment-277952015):
> It is a bit overwhelming to have that pop up every time. Can we have a less intrusive way of controlling this? Like a pop up for the first time and then a setting or a separate field "PDF with comments"?

Without complicating the UI with more buttons, the easiest solution might be a "power user" setting in the user model for always exporting comments.

**Comment by jonathanherdt** [comment]
One way to do it would be to display a checkmark in the download part as follows:

![screen shot 2017-02-16 at 09 26 21](https://cloud.githubusercontent.com/assets/6302908/23013490/1f0fbe2e-f42b-11e6-872c-4225d21e7bf6.png)

The part in the settings could look like this

![screen shot 2017-02-16 at 09 36 33](https://cloud.githubusercontent.com/assets/6302908/23013617/b4f435f0-f42b-11e6-9840-a435cddcdc98.png)

Code:

```
<div class="row">
  <div class="col-md-12">
    <div class="display">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4>PDF timesheet download settings</h4>
        </div>
        <div class="panel-body">
          <input type="radio"> Always include comments
          <br>
          <input type="radio"> Never include comments
          <br>
          <input type="radio"> Always ask me
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by chrisma** [comment]
Thanks for the effort of proposing an implementation and the mockups! This looks like a good way of approaching this.

We'd be more than happy for a pull request :)

**Comment by tbjoern** [comment]
TODO make pretty bootstrappy
