### ISSUE TITLE
Fix 'Go to current time sheet' link

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#563]
Currently, the link is broken.

WorkDay isn't relevant, what happens if a user has > 1 contracts?

![image](https://cloud.githubusercontent.com/assets/1652117/24611246/ba92a026-1881-11e7-9f3c-ce6be81c8a07.png)

**Comment by tbjoern** [comment]
changed it so a User can see the link if they have a current contract. f9332b4eae4e0e61c7289a41d1c3c63647d1ecb8

According to the time sheets controller:
`current_time_sheet = current_user.time_sheets.year(today.year).month(today.month)`
the first one is taken. if there is none it selects the first contract from
` contracts = current_user.contracts.at_date(today)`
and creates a time sheet for it.

**Comment by chrisma** [comment]
Refactored in 76ba9b0cd2da6251d73cd7dc01cfbed9c141d718
