### ISSUE TITLE
Closing time sheet handed in by HiWi?

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#575]
Once a time sheet is handed in, should it still be closable? what is the semantic of that?

![image](https://cloud.githubusercontent.com/assets/1652117/25658936/ada36846-3005-11e7-9549-4acbeadf1417.png)

**Comment by derari** [comment]
When I get a physical signature while the time sheet is pending I don't need an accept anymore --> TS can be closed

**Comment by chrisma** [comment]
Wouldn't accepting a handed in time sheet without adding a signature be basically the same as closing it?

**Comment by chrisma** [comment]
![img_20170504_111517](https://cloud.githubusercontent.com/assets/1652117/25700034/13011632-30c6-11e7-8039-5fe8b97978c3.jpg)

**Comment by chrisma** [comment]
Tested in `spec/features/time_sheet/close_reopen_spec.rb`
