### ISSUE TITLE
Allow submitting signed time sheet to chair admin

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#584]
After both the HiWi and the WiMi have signed a time sheet, it should be possible to submit the time sheet to the chair admin for further processing.

- [x] Talk to administration on whether this would incur too much additional overhead vs. printing it yourself and handing it in in physical form. **accepted by admin**
- [x] After the time sheet was submitted (with a signature) by the HiWi and the time sheet was approved by the WiMi (with a signature), the time sheet should be submitted to the chair admin.
(Should this be automatic or require an additional button click?)
- [x] New event for submitting the time sheet
- [x] Send email to chair admin with attached signed time sheet
- [x] Before an email is sent, require confirmation in the form of `This will send the signed time sheet to <admin@chair.com>. Continue?`
- [x] Possibly disallow chair admin to unsubscribe from these emails via the E-Mail settings.

**Comment by tbjoern** [comment]
> Possibly disallow chair admin to unsubscribe from these emails via the E-Mail settings.
is this still wanted ?

**Comment by chrisma** [comment]
I would argue yes. It definitely doesn't make any sense to submit a time sheet only to not have the chair admin chair be notified of it, as notifications are off. The chair admin is unlikely to check the system for submitted time sheets regularly. E-Mails by the system with filled out time sheets are likely to be the most used interaction with the system by an admin. It should not be possible to unsubscribe from them, it disables a crucial part of the system, imho.

**Comment by tbjoern** [comment]
TODO: remove unsubscribe admin mail functionality
