### ISSUE TITLE
Missing time sheets older than 2 months should be automatically archived

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#592]
Currently, time sheets stay open indefinitely, unless someone manually closes / archives them. This leads to many open time sheets.

They should be closed after 2 months. After that, the time sheet can be reopened by the WiMi, in order to edit it.

Cron job?

**Comment by chrisma** [comment]
Is this still necessary when we have #593 ?

**Comment by tbjoern** [comment]
write a test for this
