### ISSUE TITLE
Remove contract information of other HiWis on chair's page

### ISSUE THREAD

**Issue by toniSta** [hpi-swt2/wimi-portal#595]
As a HiWi, I shouldn't see contracts of other HiWis having more than one contract or none on the chair's page. Additionally, there is a button for people having more than one contract, which links to my own contract.

![image](https://user-images.githubusercontent.com/11941962/27246379-776319b6-52f1-11e7-92e8-f3759df41ff5.png)

**Comment by chrisma** [comment]
Thanks for the report!
Would be nice to have a test for this, for  starters.

**Comment by tbjoern** [comment]
https://github.com/hpi-swt2/wimi-portal/commit/75d185da706e77c20a4b9e54ad6ac60b7cc7905e

**Comment by tbjoern** [comment]
add if statement instead of select

**Comment by tbjoern** [comment]
render a seperate button for each contract
