### ISSUE TITLE
Change position of "Edit user" button on profile page

### ISSUE THREAD

**Issue by toniSta** [hpi-swt2/wimi-portal#596]
The "Edit user" button on the profile page is misplaced, so that its label is truncated.

![image](https://user-images.githubusercontent.com/11941962/27246564-bae1c4ac-52f2-11e7-9ad0-ae25c1d9f7de.png)

**Comment by chrisma** [comment]
![image](https://user-images.githubusercontent.com/1652117/27334651-4120c3e0-55ca-11e7-8ab7-f7e8ab1e7aa9.png)
