### ISSUE TITLE
Timesheets without project

### ISSUE THREAD

**Issue by toniSta** [hpi-swt2/wimi-portal#597]
As a new user to the system, I am able to edit my timesheet, without being a member of a project. Since I didn't belong to a project, I couldn't save my timesheet and got an error.

Expected behaviour:
As a new user of the system not belonging to a project, timesheet options ("Edit timesheet", "New timesheet", etc) should not be visible.

**Comment by chrisma** [comment]
Thanks for the report. That is a very good point.
We should have a test for this first.

**Comment by tbjoern** [comment]
add test for presence of current time sheet button
