### ISSUE TITLE
Localization issues / UI text improvement

### ISSUE THREAD

**Issue by toniSta** [hpi-swt2/wimi-portal#598]
- At contracts page, the description content varies depending on language settings: 
	- English: "Search terms are connected using "or"."
	- German: "Suchbegriffe werden mit "und" verknüpft."
- Also on contracts page: wage per hour should have 2 decimals.
- The field "Research Group:" on the profile page is empty for HiWis. Wouldn't it be better not to display it, if it is empty or display something like "Research Group: \<none\>"
- Edit user page: Missing comma in email description "Adresse **,** (!) an die E-Mail Benachrichtigungen verschickt werden"
- Edit user page: German description for staff number sounds oddly ("Optional. Wird auf Stundenzettel PDFs eingetragen"). You could insert a hyphen between "Stundenzettel" and "PDFs" or change it to someting better sounding like "Optional. Wird auf dem Stundenzettel eingetragen"

**Comment by chrisma** [comment]
Hi @toniSta , 

thanks for your reports!

**Comment by chrisma** [comment]
- [ ] At contracts page, the description content varies depending on language settings:
