### ISSUE TITLE
Login - openID-Authentifizierung

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#6]
Als Nutzer möchte ich mich über openID auf der Plattform registrieren und anmelden können.

**Acceptance**
- [ ] Ich kann mich mittels openID registrieren
- [ ] Nach der Registrierung kann ich mich mit meinem openID Account anmelden

**Comment by arneboockmeyer** [comment]
Schätzung: 15

**Comment by WGierke** [comment]
Soll es möglich sein sich sowohl über openID als auch über E-Mail/Passwort anzumelden?

**Comment by WGierke** [comment]
Wir fragen gerade die Verantwortlichen, ob es möglich ist, auf die Studenten-Identät des Users zuzugreifen und nicht nur auf seine OpenID Identität.
Hintergrund ist, dass man nicht zwingend seine Email bei der OpenID Identität hinterlegen muss.
Was passiert, wenn man wirklich nur auf die OpenID-Identität zugreifen kann, welche nicht zwingend eine Email mitschickt?
Wird ein User ohne Email angelegt?
Wird dem User ein Fehler angezeigt, dass er eine Email bei seiner OpenID Identity anlegen muss?

**Comment by WGierke** [comment]
Sollen die von openID importierten Daten (E-Mail, Name) nachträglich noch geändert werden können? @mandyklingbeil @mockingbird2

**Comment by mandyklingbeil** [comment]
@WGierke: Prinzipiell soll die E-Mail-Adresse beibehalten werden und nicht verändert werden können, der Name soll aber bearbeitet werden können.

**Comment by WGierke** [comment]
@mandyklingbeil Danke!

**Comment by WGierke** [comment]
Wenn ein User bei OpenID keine E-Mail-Adresse angegeben hat, sollen wir:
- einen Fehler ausgeben und ihm sagen, dass er erst eine bei OpenID hinterlegen muss?
- ihn registrieren, ihn aber solange dazu auffordern, eine Adresse zu speichern, bis er dies getan hat?
- etwas anderes?

**Comment by mandyklingbeil** [comment]
@WGierke: Bitte zweite Variante. Der "Registrierungsprozess" auf dem Wimi Portal sollte nicht abgeschlossen sein, bis dem User eine E-Mail-Adresse zugeordnet werden kann. Er kann vorher also keine Aktionen auf dem Portal vornehmen.

**Comment by marcelja** [comment]
Wisst ihr schon, wann ihr hiermit fertig seid und das in dev reinmergt?

**Comment by threxx** [comment]
Denke mal Mittwoch frühestens, könnte aber auch noch bisschen länger dauern
