### ISSUE TITLE
cannot resubmit timesheet after withdrawing

### ISSUE THREAD

**Issue by tbjoern** [hpi-swt2/wimi-portal#626]
as a hiwi, if i submit a timesheet and then withdraw it, i cannot resubmit the timesheet, even after editing it.
![image](https://user-images.githubusercontent.com/10194372/32367990-86173248-c084-11e7-878e-46d34f48834b.png)

this should be possible however.

relevant file: `views/time_sheets/_hand_in.html.erb`

**Comment by chrisma** [comment]
Thanks for the test for this! :+1:
