### ISSUE TITLE
"Create next time sheet" forbidden

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#630]
When I'm on a timesheet page and click "create sheet for next month", I get "You are not authorized to do that action."

**Comment by tbjoern** [comment]
I just tried this as a hiwi in the production system and it works fine. Can you give more context for reproducing this ?

**Comment by chrisma** [comment]
This is the case when the contract end in the month that is being viewed, e.g. it is not possible to create a time sheet for the next month, as no valid contract is available.

The button should not be shown in this case.

However, we should render a warning (flash message), that this is the last month of the contract.

**Comment by chrisma** [comment]
This should be fixed in the ability.rb. Build a new time sheet for the next month, check if it can be created.
