### ISSUE TITLE
Don't show old contracts on the dashboard

### ISSUE THREAD

**Issue by derari** [hpi-swt2/wimi-portal#631]
On my dashboard, I don't want to see contracts with end date older than (eg) 3 months

**Comment by chrisma** [comment]
Which pane of the dashboard are you referring to? the "contracts that end soon" one as WiMi?

**Comment by tbjoern** [comment]
![image](https://user-images.githubusercontent.com/10194372/33426335-bf039f18-d5c1-11e7-950b-6f909da4c5ba.png)
