### ISSUE TITLE
Link to contract in flash notice after inviting user to project

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#633]

**Comment by tbjoern** [comment]
This does not seem to be possible atm. We would have to use `sanitize` in our view, however flash messages are rendered with `boostrap_flash` from the boostrap gem. Thus we cant change it.

https://stackoverflow.com/questions/24887814/rails-4-link-in-flash-message-is-not-parsed-as-html

**Comment by chrisma** [comment]
ok, if the message is yellow (warning) it should give enough indication, even without linking directly.
