### ISSUE TITLE
FG-Beauftragter - Dashboard Benachrichtigungen //23P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#64]
Als Beauftragter eines Fachgebiets möchte ich zusätzlich zu den Benachrichtigungen eines regulären Wimi über sämtliche Aktivitäten, die mich in meiner Rolle als FG-Beauftragter betreffen, eine Benachrichtigung auf meinem Dashboard bekommen.

**Akzeptanzkriterien**
- [x] Ich erhalte eine Benachrichtigung, wenn ein Wimi von meinem Fachgebiet einen Urlaubsantrag gestellt hat
- [x] Ich erhalte eine Benachrichtigung, wenn ein Wimi von meinem Fachgebiet einen Dienstreise-Antrag gestellt hat
- [x] Ich erhalte eine Benachrichtigung, wenn ein Wimi von meinem Fachgebiet, eine Reisekostenabrechnung eingereicht hat
- [x] Die Benachrichtigung verlinkt auf den entsprechenden Antrag

![capture](https://cloud.githubusercontent.com/assets/9438971/11625315/5ddbf1b2-9cda-11e5-9390-ae59f01e5566.PNG)

**Comment by tbjoern** [comment]
@Chaoste @sebastian-ernst ist das Issue fertig ? Wenn ja dann setzt bitte das Label auf ready for review.
