### ISSUE TITLE
Cannot add / edit time sheets after contract end

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#642]
It is not possible to add any new time sheets or edit existing time sheets of a contract if the current date is after the end of the contract.
It should be possible to add / edit all time sheets.

**Comment by tbjoern** [comment]
The issue is, that new/create on Timesheets is only allowed when `user.current_contract.any?` is `true`. We need a clever way to incorporate the corresponding contract into the ability check.

**Comment by tbjoern** [comment]
i removed the `user.current_contract.any?` check, since the `TimeSheet` model already validates that the associated contract is valid in the selected month.
