### ISSUE TITLE
Allow superadmin to be super

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/wimi-portal#644]
E.g. show all contracts!

**Comment by tbjoern** [comment]
Note: the superadmin has to be assigned to a chair (corresponding chair_wimi entry has to exist). Otherwise many pages will break, since they assume that users with certain permissions have a chair.

**Comment by chrisma** [comment]
As a workaround, assign superadmin to the first chair in the system

**Comment by tbjoern** [comment]
think about a good solution for this.
