### ISSUE TITLE
Projekt - User zu einem Projekt einladen // 2

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#65]
Als Wimi kann ich User zu meinem Projekt einladen. (Grafik aus #43)

- Auf "Jemanden in das Projekt einladen" klicken und über ein Modal einen Nutzer auswählen und zum Projekt einladen

**Akzeptanzkriteirum**

- [ ] Nach Klick auf "Jemanden in das Projekt einladen" öffnet sich ein Modal. Hier wird ein Suchfeld zur Nutzersuche angezeigt und ein ausgewählter Nutzer lässt sich in das Projekt einladen (mit Benachrichtigung)

**Comment by WGierke** [comment]
Erhält der eingeladene Nutzer eine einfache Benachrichtigung, wenn er sich wieder einloggt oder erhält er eine E-Mail mit Link zum WiMi-Portal und Projekt? So kann man auch Nutzer hinzufügen, die nicht bereits registriert sind.
Wenn der eingeladene Nutzer bereits registriert ist, ist er dem Projekt dann bereits hinzugefügt oder muss er die Einladung noch annehmen?

**Comment by mandyklingbeil** [comment]
Eine Einladung soll nur an Nutzer möglich sein, die bereits registriert sind. E-Mails sind an dieser Stelle nicht notwendig.

Prinzipiell ist die Idee, dass es Benachrichtigungen auf dem Dashboard darüber gibt. Es würde an dieser Stelle reichen, wenn der eingeladene Nutzer ab sofort dem Projekt als Mitglied hinzugefügt ist.

**Comment by WGierke** [comment]
Alles klar, danke :+1:

**Comment by WGierke** [comment]
Aus #43 : Das Einladen zu einem Projekt wird rollenspezifisch. Wenn man einen bestehenden WiMi einlädt, wird dieser WiMi des Projekt. Falls der User noch keine Rollte hatte wird dieser HiWi. Schon angemeldete HiWis bleiben ganz normal bei der Rolle HiWi.

**Comment by WGierke** [comment]
@mockingbird2 @sleighsoft @mandyklingbeil Das Ticket wartet noch auf die Implementierung der Rollen aus #7 und #32 von @NHoff95 @marcelja @swt-r0ckz. Ansonsten ist das Feature fertig.
