### ISSUE TITLE
User - Beitritt zu einem Lehrstuhl // 5

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#7]
Als 'User' kann ich alle Lehrstühle einsehen.
Als 'User' kann ich mich bei einem Lehrstuhl als 'WiMi' bewerben.
Meine Bewerbungen und deren Status kann ich einsehen.
Akzeptiert mich ein 'Administrator' des Lehrstuhls, so bin ich ein 'WiMi' dieses Lehrstuhls.

Rollen: User, Administrator(Lehrstuhl), WiMi

**Akzeptanzkriterien**
- [ ] Aus einer Liste aller verfügbaren Lehrstühle kann einer ausgewählt werden und es kann eine Bewerbung an diesen gesendet werden
- [ ] Nach Versendung einer Bewerbung kann ich deren Status einsehen
- [ ] Nachdem die administrative Person die Zugehörigkeit eines WiMis zum Lehrstuhl bestätigt, ist der 'User' dem Lehrstuhl als 'WiMi' zugeordnet.

**Comment by arneboockmeyer** [comment]
Schätzung: 10

**Comment by NHoff95** [comment]
Kann man WiMi bei mehreren Lehrstühlen sein bzw. sich bei mehreren (gleichzeitig) bewerben?

**Comment by mandyklingbeil** [comment]
@NHoff95: Man kann sich nur in einem Lehrstuhl eintragen/bewerben. Wenn man an einem Lehrstuhl eingetragen ist, dann kann man sich nicht in weitere Lehrstühle eintragen. Erst, wenn man seinen Lehrstuhl verlässt, kann man sich wieder in einen neuen Lehrstuhl eintragen.

**Comment by arneboockmeyer** [comment]
Neue Schätzung: 5

**Comment by mockingbird2** [comment]
@NHoff95 Könntest du dich bitte mit den Leuten aus #32 in Verbindung setzen. Sie haben zusätzlich deine Funktionalität übernommen um ihre Story zu implementieren. Vielleicht könnte man euren Code mergen und schneller in Production übernehme.

**Comment by WGierke** [comment]
Ein Merge in den dev mit Pull-Request wäre nicht schlecht, weil auch andere Tickets eine Rollenbeteiligung haben. @NHoff95 @marcelja @swt-r0ckz
