### ISSUE TITLE
Profil - Unterschrift hinzufügen und verschlüsseln // 6P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#73]
Siehe aus Sprint 1: #11 und #35

Als Nutzer möchte ich meine eingescannte/fotografierte Unterschrift hochladen können, sodass ich diese später zum Unterschreiben auf Dokumenten benutzen kann. Die Unterschrift verschlüsselt abgespeichert werden.

**Acceptance Tests**
- [ ] Ich kann eine Unterschrift im Profil hochladen 
- [ ] Nur ich kann die hochgeladene Unterschrift einsehen
- [ ] Ich kann die hochgeladene Unterschrift löschen
- [ ] Die Unterschrift ist verschlüsselt gespeichert.

**Atomic Tasks**
- [x] Drei Buttons im Profil einfügen: Unterschrift ansehen(1) , Unterschrift hochladen(2), Unterschrift löschen (3)
- [ ] (1) hier muss sich eine Eingabemaske öffnen in der der User aufgefordert wird sein passwort einzugeben, falls es stimmt wird das eins hochgeladene Bild angezeigt ==> Vorraussetzung hierfür ist, dass das Bild verschlüsselt in der Datenbank vorliegt + dass ein Passworthash gespeichert ist
- [ ] (2) Hier gibt man zum Hochladen ein Passwort ein, dann wird das Bild und Passwort verschlüsellt abgespeichert
- [ ] hierfür muss zusätzlich ein Verschlüsselungsalgorithmus geschrieben werden
- [ ] (3)Hier wird lediglich der Eintrag in der Datenbank gelöscht
- [ ] Nach jeder Aktion muss ein Acknowledgement fenster aufleuchten
- [ ] Man muss sicher stellen, dass kein andere Zugriff auf die Unterschriften hat, als zusätzliche Maßnahme
- [ ] es muss Funktionalität für das erreichen und entschlüsseln des Bildes in der Datanbank bereitgestellt werden, damit es problemlos von zukünftigen Entwicklern genutzt werden kann.

**Comment by tbjoern** [comment]
Wird in Issue #11 bearbeitet.
