### ISSUE TITLE
Profil - Localization / Sprachen // 5P

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#76]
Siehe aus Sprint 1: #20.

Als Nutzer möchte ich das System bevorzugt auf Deutsch benutzen. Ich möchte aber die Möglichkeit haben, die Sprache auf Englisch umzuschalten. Default: Englisch
Tipp: http://guides.rubyonrails.org/i18n.html

Bitte nach Implementierung andere Teams über Verwendung informieren.

**Acceptance**
- [x] Ich kann die bevorzugte Sprache in meinem Profil einstellen.
- [x] Alle Texte werden in der vom Nutzer gewählten Sprache angezeigt.

**Atomic Tasks**
- [x] Änderung der Sprache für jeden ermöglichen
- [x] Spracheinstellung für jeden Nutzer speichern und bei Login anwenden
- [x] Übersetzungsdateien schreiben
- [x] Wiki-Guide für Localization schreiben

**Comment by bahnfahren** [comment]
Bitte zusätzlich noch einen Eintrag im wiki machen damit alle Devs wissen wie "lokalisiert" werden kann.

**Comment by WGierke** [comment]
Ist es möglich, auch noch date/time localization hinzuzunehmen?
Dann hätten wir auch schön formatierte Zeitangaben :)
Die ersten 55 Zeilen sollten das schon schaffen: https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/de.yml

**Comment by mmkonrad** [comment]
Ohne Angabe des Datumsformats gehts sowieso nicht.
Doch gibt es denn einen Fall, wo auch mit ausgeschriebenen Datumsangaben gearbeitet wird? 
alles was ich bisher gesehen habe benutzt Datumsangaben mit Zahlen.

**Comment by WGierke** [comment]
Das Standard-Format wird in de.dates.formats.default angegeben und kann einfach über zb 
<%= l Time.now %>
Verwendet werden. 
Die verlinkte YAML Datei sollte zum Beispiel Monate ausschreiben, was kein Problem ist, da deren deutsche Bezeichnungen mit angegeben sind. 
Copy & Paste sollte also reichen :)
Oder hab ich dich falsch verstanden?

**Comment by mmkonrad** [comment]
Aktuell in der en.yml bzw. de.yml enthalten (denn ohne geht es nicht aka exceptions):
  time:
    formats:
      default: "%d/%m/%Y"
      short: "%b %d"
      long: "%B %d, %Y"

Default entsprechend der Sprache. 

Meine Frage bezog sich auf die ausgeschriebenen, bzw. abgekürzten Wochentage/Monate. Wenn sie verwendet werden, dann gehören sie darein. Wenn nicht, dann muss man die Dateien nicht mit ungenutztem Inhalt aufblähen.
Daher die Frage: Werden ausgeschriebene Daten verwendet ja/nein?
Wenn ja, dann nehme ich es mit rein. 
Abgesehen davon sollen zusätzliche Übersetzungen später von den Implementoren selbst eingefügt werden, da wohl niemand für den Rest des Projektes dediziert für Lokalisation eingeteilt sein wird oder?

**Comment by WGierke** [comment]
Achso alles klar.
short und long verwenden im Moment ja schon %b bzw %B was den abgekürzten bzw vollen Monatsnamen zurückgibt. Das ist natürlich eine potentielle Fehlerquelle, wenn keine Monatsnamen mitgespeichert werden.
Was könnte sich der Kunde wünschen @mandyklingbeil ? Möchte er auch mal ausgeschriebene Monatsnamen sehen?
Ich kann mir nicht vorstellen, dass jemand dazu degradiert werden sollte.

**Comment by mandyklingbeil** [comment]
@mmkonrad, @WGierke: Ja, prinzipiell ist es wünschenswert, an bestimmten Stellen auch ausgeschriebene Monatsnamen zu sehen. Es wird sicher an irgendeinem Punkt kommen, weil reine Zahlen optisch ggf. nicht so "greifbar" sind, gerade, wenn ich mir viele verschiedene Daten/Zahlen anschaue. Ob wir diesen Punkt in den 4 Sprints erreichen, weiß ich nicht. Ich persönlich würde ja sagen, dass derjenige, der dann erstmals mit ausgeschriebenen Monaten zu tun hat, diese auch einfach mit in die yaml-Dateien einfügen könnte. Aber das überlasse ich euch.

**Comment by mmkonrad** [comment]
Deal
