### ISSUE TITLE
User - Projektbewerbung // 2

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#8]
Als 'User' kann ich alle öffentlichen Projekte aller Lehrstühle einsehen.
Aus dieser Liste kann ich ein Projekt auswählen und mich auf dieses als 'HiWi' bewerben.
Meine Bewerbungen und deren Status kann ich einsehen.
Werde ich durch einen 'WiMi' des Projekts bestätigt, so bin ich ein 'HiWi' des Projekts.

**Akzeptanzkriterien**
- [ ] Aus einer Liste aller öffentlichen Projekte kann eines ausgewählt werden und es kann eine Bewerbung an dieses gesendet werden
- [ ] Nach Versendung einer Bewerbung kann ich deren Status einsehen
- [ ] Nachdem ein 'WiMi' des Projekts die Zugehörigkeit zum Projekt bestätigt, bin ich 'HiWi' dieses Projekts

![image](https://cloud.githubusercontent.com/assets/9438971/11865281/5cb21354-a4a3-11e5-85ae-31c36d08608c.png)

**Comment by arneboockmeyer** [comment]
Schätzung: 10

**Comment by shorschig** [comment]
Soll es immer (für jeden User) nur eine Bewerbung zu einem Projekt geben?

Kontext: Ich habe mich für ein Projekt beworben und wurde abgelehnt. Wenn ich jetzt auf die Liste meiner Bewerbungen gehe, sehe ich die abgelehnte Bewerbung und will es noch einmal versuchen und mich wieder bewerben. Soll die abgelehnte Bewerbung aus der Liste entfernt und nur die neue, ausstehende angezeigt werden oder weiterhin beide in der Liste bestehen?

**Comment by mandyklingbeil** [comment]
@shorschig: Die abgelehnte Bewerbung kann aus der Liste entfernt werden, sodass nur die neue, ausstehende Bewerbung angezeigt wird.
