### ISSUE TITLE
FG-Beautftragter - Dashboard

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#87]
Diese User-Story beschreibt, was ein FG-Beauftragter auf seinem Dashboard angezeigt bekommt und welche Aktionen dort unternommen werden können. Sie dient als Zusammenfassung mehrerer User-Stories und gilt als erfüllt, wenn alle refererenzierten User-Stories erfüllt sind.

**Akzeptanzkriterien**
- [x] Aktionen - Issue #46
- [x] Benachrichtigungen - Issue #64 

![capture](https://cloud.githubusercontent.com/assets/9438971/11625315/5ddbf1b2-9cda-11e5-9390-ae59f01e5566.PNG)

**Comment by marcelja** [comment]
Benachrichtigungen und "LS-Beauftragter - Aktionen" sind fertig
