### ISSUE TITLE
Login - User ohne Projekt/Lehrstuhl // 8

### ISSUE THREAD

**Issue by mockingbird2** [hpi-swt2/wimi-portal#88]
Wenn ich mich initial auf der Seite angemeldet habe. Sehe ich eine Seite auf der ich mich auf Lehrstühle bewerben kann und Einladungen annehmen kann zu Projekten.

**Akzeptenzkriterien**
- [ ] Als User sehe ich alle Lehrstühle
- [ ] Neben jedem Lehrstuhl gibt es einen Button "Bewerben"
- [ ] Wenn ich mich auf einen Lehrstuhl beworben habe ändert sich der Button "Bewerben", des Lehrstuhls, zu einem Label "Gestellt"
- [ ] Einladungen werden angezeigt und lassen sich annehmen und ablehnen
- [ ] Wurde ich zu einem Lehrstuhl angenommen oder habe einer Projekteinladung zugestimmt komme ich nicht mehr auf diese Seite
- [ ] Der User kann sich zugleich nur bei einem Lehrstuhl bewerben

![capture](https://cloud.githubusercontent.com/assets/9438971/11880172/85fc37a6-a4ff-11e5-9711-31fa523bd1d1.PNG)

![capture](https://cloud.githubusercontent.com/assets/9438971/11880203/ad7e859a-a4ff-11e5-8f87-8ba87d0ab2a3.PNG)

**Comment by NHoff95** [comment]
@mockingbird2 Theoretisch würde es sich hier anbieten, das im Dashboard zu integrieren, wo ja eh je nach User verschiedene Sachen angezeigt werden. Wäre dies in Ordnung oder muss es eine extra Seite sein?

**Comment by mockingbird2** [comment]
Es könnte auch das "Dashboard" eines Users ein. Aber es sollen keine anderen Funktionen sichtbar sein oder gar ausführbar.

**Comment by NHoff95** [comment]
Natürlich, das ist kein Problem. Danke

**Comment by NHoff95** [comment]
- [ ] Liste vorhandener Lehrstühle
- [ ] Möglichkeit, Bewerbung abzuschicken
- [ ] Status der Bewerbung anzeigen
- [ ] Projekteinladungen anzeigen
- [ ] Seite nur anzeigen, wenn noch keinem Lehrstuhl/Projekt zugehörig

**Comment by arneboockmeyer** [comment]
@NHoff95 was ist der aktuelle stand?

**Comment by NHoff95** [comment]
@arneboockmeyer Ist soweit fertig und ist im team1review-Branch zur Abnahme
