### ISSUE TITLE
Superadministrator - Dashboard // 3

### ISSUE THREAD

**Issue by sleighsoft** [hpi-swt2/wimi-portal#89]
Auf meinem Dashboard sehe ich alle verfügbaren Lehrstühle und kann neue erstellen.

**Akzeptanzkriterien**
- [ ] Ich sehe alle verfügbaren Lehrstühle
- [ ] Ein Klick auf einen Lehrstuhl führt mich zu einer Detailseite von diesem
- [ ] Es gibt ein Button "Lehrstuhl hinzufügen" der auf eine Seite zum Erstellen neuer Lehrstühle verlinkt

![capture](https://cloud.githubusercontent.com/assets/9438971/11623997/f06b4d34-9cd0-11e5-9c02-c4e914de36a7.PNG)

**Comment by NHoff95** [comment]
Wie kann ich mir die Detailseite der Lehrstühle vorstellen, die vom Dashboard aus bei Klick auf den Lehrstuhl erreichbar sein soll? Bisher war es ja so, dass die Detailseite den Lehrstuhl-Beauftragten und Lehrstuhl-Admins vorbehalten ist und nur diese Details wie Wimis, Hiwis, usw. sehen/bearbeiten können. Ändert sich dies nun mit dieser Story? Oder welche anderen Informationen sollen dort noch stehen?

**Comment by mockingbird2** [comment]
Die details seite des Lehrstuhls ist nicht Inhalt dieser Story. Du musst dich nicht um den Entwurf dieser Seite kümmern. Redirect einfach auf die bestehende.

**Comment by NHoff95** [comment]
@mockingbird2 Naja, ist so aktuell drin, aber die bestehende Detail-Seite verwehrt dem Superadmin z. Z. den Zugriff, da sie ja eigentlich nicht für ihn gedacht war. Soll das trotzdem erstmal so bleiben oder soll der Link dann erstmal raus? Ansonsten müsste die Detail-Seite nochmal so angepasst werden, dass der Superamin zwar Zugriff hat, aber nicht alles sieht/machen darf...

**Comment by mockingbird2** [comment]
Die Detailseite des Superadmins für den Lehrstuhl wird Teil einer anderen User Story. Der link soll dort bleiben.

**Comment by NHoff95** [comment]
OK, danke

**Comment by NHoff95** [comment]
Tasks:

- [x] Liste vorhandener Lehrstühle
- [x] Möglichkeit, Lehrstühle hinzuzufügen
- [ ] Link führt zu Detailseite
