### ISSUE TITLE
WiMi - Projekte erstellen // 5

### ISSUE THREAD

**Issue by mandyklingbeil** [hpi-swt2/wimi-portal#9]
Als 'WiMi' eines Lehrstuhls möchte ich ein Projekt erstellen, bearbeiten und auf aktiv/inaktiv setzen können. Ich werde beim Erstellen automatisch dem Projekt zugeordnet. Außerdem wird das erstellte Projekt dem Lehrstuhl zugeordnet, dem ich angehöre.

**Akzeptanzkriterien**
- [ ] Nach Erstellen eines Projekts gibt es ein neues Projekt im System, das dem entsprechenden Lehrstuhl angehört
- [ ] Als 'WiMi' dieses Projekts habe ich die Möglichkeit meine eigenen (Projekte in denen ich WiMi bin) zu bearbeiten, verlassen und auf aktiv/inaktiv zu setzen

**Comment by arneboockmeyer** [comment]
Schätzung: 9

**Comment by threxx** [comment]
*Tasks: *

- [ ] Nach Erstellen eines Projekts gibt es ein neues Projekt im System, das dem entsprechenden Lehrstuhl angehört
- [ ] Als 'WiMi' dieses Projekts habe ich die Möglichkeit meine eigenen (Projekte in denen ich WiMi bin) zu bearbeiten, verlassen und auf aktiv/inaktiv zu setzen
